### ISSUE TITLE
Attempting to run a container with sudo -u <user> fails

### ISSUE THREAD

**Issue by Nathan22211** [igo95862/bubblejail#102]
I had a sudoers rule that allowed me to run commands as a non root user without needing to enter a password. However, even if that other user had a bubblejail container of the app, it would just error.

If you want to replicate it. You can install ego from the AUR if on arch, as what it does is very similar, and try to run a container with it.

**Comment by igo95862** [comment]
Hello @Nathan22211 

This is not entirely an intended use if the bubblejail.

Most likely the issue is that pure `sudo -u` does not create a XDG_RUNTIME_DIR. Can you post some logs?

**Comment by Nathan22211** [comment]
Waiting for bitwarden to install but it seems to be a permissions issue so far with the toml file

**Comment by Nathan22211** [comment]
`Traceback (most recent call last):
  File "/usr/bin/bubblejail", line 32, in <module>
    bubblejail_main()
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 243, in bubblejail_main
    func(**args_dict)
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 80, in run_bjail
    instance = BubblejailDirectories.instance_get(instance_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_directories.py", line 86, in instance_get
    convert_old_conf_to_new()
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_directories.py", line 49, in convert_old_conf_to_new
    if (instance_directory / FILE_NAME_SERVICES).is_file():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 892, in is_file
    return S_ISREG(self.stat().st_mode)
                   ^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 840, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/ego/.local/share/bubblejail/instances/chromium/services.toml'
`
going to try chmodding the folder

**Comment by igo95862** [comment]
Is `ego` your username or the username of a `sudo -u <username>`?

**Comment by Nathan22211** [comment]
ffs wrong thing

**Comment by igo95862** [comment]
> `Traceback (most recent call last): File "/usr/bin/bubblejail", line 32, in <module> bubblejail_main() File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 243, in bubblejail_main func(**args_dict) File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 82, in run_bjail if instance.is_running(): ^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_instance.py", line 194, in is_running return self.path_runtime_helper_socket.is_socket() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/functools.py", line 995, in __get__ val = self.func(instance) ^^^^^^^^^^^^^^^^^^^ File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_instance.py", line 80, in path_runtime_helper_socket return self.path_runtime_helper_dir / 'helper.socket' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/functools.py", line 995, in __get__ val = self.func(instance) ^^^^^^^^^^^^^^^^^^^ File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_instance.py", line 76, in path_runtime_helper_dir return self.runtime_dir / 'helper' ^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/functools.py", line 995, in __get__ val = self.func(instance) ^^^^^^^^^^^^^^^^^^^ File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_instance.py", line 59, in runtime_dir return Path(get_runtime_dir() + f'/bubblejail/{self.name}') ^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/site-packages/xdg/BaseDirectory.py", line 141, in get_runtime_dir return os.environ['XDG_RUNTIME_DIR'] ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^ File "<frozen os>", line 685, in __getitem__ KeyError: 'XDG_RUNTIME_DIR' `

This is exactly what I expected. Bubblejail is meant to be run in desktop environment where XDG_RUNTIME_DIR is present.

You can use the `sudo machinectl shell --uid=ego` to run in the environment with the necessary variables but otherwise at the moment I don't have any intentions in supporting running it with `sudo -u`.
