### ISSUE TITLE
[UI]: App icon on KDE Wayland uses generic Wayland one

### ISSUE THREAD

**Issue by boredsquirrel** [igo95862/bubblejail#103]
### Output of `bubblejail --version`

0.8.3

### Your distro name and version

Fedora Kinoite 40

### Description

The Bubblejail app runs as "python3" with the "sub-name" (?) "bubblejail-config".

This is not recognized as the desktop entry and thus uses the default Wayland icon.

**Comment by igo95862** [comment]
Hello @boredsquirrel 

Are you talking about configuration utility `bubblejail-config`? The icon works fine on my machine using GNOME 46 Wayland. Is this something Fedora specific?

**Comment by rusty-snake** [comment]
To clarify, the icon in launcher menus works but in bars listing running programs/open windows the association (from window to app to .desktop) fails.

**Comment by igo95862** [comment]
Now I understand which icon you are talking about.

I made a commit 4b44463c1b379ae33fd84bb7da0eded20285f286 which maybe fixes the issue. Could you give it a test?

**Comment by rusty-snake** [comment]
WFM

**Comment by igo95862** [comment]
I plan on adding this commit for the next 0.9.0 version.
