### ISSUE TITLE
Allow deleting profiles

### ISSUE THREAD

**Issue by boredsquirrel** [igo95862/bubblejail#104]
### Description

0.8.3 Fedora Kinoite

There is no right-click option or a different GUI way to delete a profile. 

Workaround: delete manually in `~/.local/share/bubblejail/instances/` and `~/.local/share/applications/`

**Comment by igo95862** [comment]
Hello @boredsquirrel 

Are you talking about a profile or an instance? There is already an issue about deleting instances: #48
