### ISSUE TITLE
gamemode functionality inside of bubblejailed program

### ISSUE THREAD

**Issue by odomingao** [igo95862/bubblejail#109]
### Description

bubblejail works very well for sandboxing games and launchers/wine managers like steam and bottles, however performance is very poor due to the non-availability of gamemode. Are there any workarounds currently to get it working? If not, would it be possible to implement one?

**Comment by igo95862** [comment]
Hello @odomingao 

It looks like gamemode can run in daemon mode where a PID can be passed to activate the gamemode for a specific processs: https://github.com/FeralInteractive/gamemode/tree/master/daemon

It also looks like it has a D-Bus API that you can probably pass to the sandbox.

**Comment by odomingao** [comment]
> Hello @odomingao
> 
> It looks like gamemode can run in daemon mode where a PID can be passed to activate the gamemode for a specific processs: https://github.com/FeralInteractive/gamemode/tree/master/daemon
> 
> It also looks like it has a D-Bus API that you can probably pass to the sandbox.

Yes, this seems to work! Thank you @igo95862 :)

**Comment by guilty-p01nt3r** [comment]
May I ask some instructions in how to do that ?

**Comment by odomingao** [comment]
@guilty-p01nt3r 

You can run `gamemoded -r` on the pid of the game. To get the pid for an active window it varies per compositor, but on Hyprland I have this binded:  `killall gamemoded; hyprctl activewindow -j | jaq -r '.pid' | xargs gamemoded -r`

If your program already supports gamemode, you can add the following to allow talking to the d-bus:

```
[debug]
raw_dbus_session_args = [
    "--talk=com.feralinteractive.GameMode",
]
```

and it should work.
