### ISSUE TITLE
Расширение сферы применения BubbleJail. Изолированные рабочие столы (окружения).

### ISSUE THREAD

**Issue by ls0h** [igo95862/bubblejail#11]
Привет! 

Что если использовать BubbleJail не только для отдельных приложений, но и для окружения рабочего стола, либо некоторой его части? В KDE есть инструмент под названием Activities. Я не уверен, есть ли что-то подобное в GNOME или там обычные рабочие столы. KDE Activities позволяет создавать что-то вроде виртуальных рабочих столов, добавлять на них виджеты (различные для разных Activity), делать некоторые настройки отличными от общих, прикреплять окна приложений и т. п. Но при этом приложения на разных Activity не ограничены друг от друга, имеют общие настройки, директории, т.п. 

Суть идеи. Запускать в  BubbleJail некоторое подмножество процессов, составляющих окружение рабочего стола.
Это опциональная функция, т.е. запуск отдельных приложений никуда не денется.

Полезные применения:
* Приватные окружения. Это как приватный режим в браузере, но для виртуального рабочего стола. При запуске домашняя директория создаётся в tmpfs, пользователь получает чистое окружение, при его закрытии всё удаляется. Например, пользователь может скачать какой-либо приватный (секретный) документ, отредактировать его, отправить по электронной почте. Во время этого пользователь не оставит никаких следов на компьютере, документ не попадёт в список недавних, файловый менеджер не сделает миниатиру для файла и т. п. Это лучше, чем приватный режим работы браузера, т. к. охватывает больше аспектов.
* Отдельные тематические окружения. Например, окружение для работы и окружение для отдыха. В разных окружениях могут быть запущены разные экземпляры одного и того же браузера, с разной историей. Это удобно, в рабочем браузере история будет содержать только страницы документации, проектов, репозиториев, т. е. ничего лишнего. В этом же виртуальном окружении будет запущен IDE. При кликах на ссылки документации из IDE они будут открываться в браузере в этом же окружении. Так же можно запустить несколько экземпляров одного и того же мессенджера. Например, один для рабочих контактов, другой для семьи. Мессенджеры могут и не поддерживать работу с разными аккаунтами одновременно. Но, благодаря разным окружениям, это не проблема. Пользователь может выбирать разные темы для приложений, чтобы легче переключаться между работой и домашними делами. При этом некоторые директории, вроде Downloads могут оставаться общими.

Что для этого нужно?
* Выбрать окружение для интеграции. Пока наиболее близкие возможности я нашёл в KDE. Но это не обязательно, можно попробовать и GNOME.
* Определить список процессов, которые должны запускаться в изолированном окружении. Я думаю, там должен быть свой dbus daemon. Не proxy, а именно daemon. Это для того, чтобы межпроцессные коммуникации происходили только внутри окружения, настройки не перемешивались. так же внутри будут свои служебные процессы, характерные для выбранного DE. Однако, оконный менеджер и всевозможные панели там запускать не надо, они останутся общими для всех окружений. В результате нам нужно что-ото вроде профиля для BubbleJail, со списком процессов, которые надо запускать внутри.
* Сделать расширение для оконного менеджера, которое будет проверять, где запущено приложение (в каком BubbleJail окружении) и принудительно переносить его на нужный рабочий стол или Activity. Возможно хватит простого скрипта. Определять можно по выставляемым переменным окружения `export BJ_SUB_DE="work"`, `export BJ_SUB_DE="games"`.
* Сделать возможность запуска приложений в разных окружениях. Возможно для этого всё же понадобится запускать разные экземпляры панели задач (или только апплета с главным меню), какие-то внутри изолированного окружения, какие-то вне его.

**Comment by igo95862** [comment]
> Приватные окружения. Это как приватный режим в браузере, но для виртуального рабочего стола. При запуске домашняя директория создаётся в tmpfs, пользователь получает чистое окружение, при его закрытии всё удаляется. Например, пользователь может скачать какой-либо приватный (секретный) документ, отредактировать его, отправить по электронной почте. Во время этого пользователь не оставит никаких следов на компьютере, документ не попадёт в список недавних, файловый менеджер не сделает миниатиру для файла и т. п. Это лучше, чем приватный режим работы браузера, т. к. охватывает больше аспектов.

Это есть в планах и даже описано в TODO файле.

> В разных окружениях могут быть запущены разные экземпляры одного и того же браузера, с разной историей. Это удобно, в рабочем браузере история будет содержать только страницы документации, проектов, репозиториев, т. е. ничего лишнего. В этом же виртуальном окружении будет запущен IDE. При кликах на ссылки документации из IDE они будут открываться в браузере в этом же окружении. Так же можно запустить несколько экземпляров одного и того же мессенджера. Например, один для рабочих контактов, другой для семьи. Мессенджеры могут и не поддерживать работу с разными аккаунтами одновременно.

Это уже возможно если создать несколько Instance для одной и той же программы. Однако не все программы будут хорошо работать. Например `Firefox` на `X11` нужно дать `--class` и `--name` параметры или он будет сам себя запускать. Для каждой программы нужно проводить исследование. Нет универсального способа.

> Сделать расширение для оконного менеджера

Ну это точно за рамками проэкта. 

Для KDE я рекомендую [KWin scripts](https://techbase.kde.org/Development/Tutorials/KWin/Scripting)

**Comment by ls0h** [comment]
> Это есть в планах и даже описано в TODO файле.

Прошу прощения, этот пункт не заметил. :-)

>Например Firefox

Хм... Я пробовал запускать Firefox, он не обнаруживал другие свои экземпляры, вёл себя как запущенный в первый раз. Попробую ещё.

А что ты думаешь расширение профилей? Добавить некий механизм, который будет запускать частичное окружение внутри контейнера. Dbus daemon, kded5, kwallet и т.п.. Т.е. KDE, но без Plasma и Kwin. И для GNOME что-то аналогичное. Сейчас он у меня не установлен.

**Comment by igo95862** [comment]
> А что ты думаешь расширение профилей? Добавить некий механизм, который будет запускать частичное окружение внутри контейнера. Dbus daemon, kded5, kwallet и т.п.. Т.е. KDE, но без Plasma и Kwin.

Можно но в будущем. Сейчас приоритет `python-sdbus` > интерфейс на D-Bus и GTK > внутри сандбоксовый помошник на D-Bus > запуск приложений изнутри в наружу через специальный фильтр
