### ISSUE TITLE
add "--talk=org.freedesktop.portal.Desktop" with the pipewire permission?

### ISSUE THREAD

**Issue by odomingao** [igo95862/bubblejail#119]
### Description

Hello,

`"--talk=org.freedesktop.portal.Desktop"` is needed for pipewire screensharing to work with browsers and obs, at least in Hyprland. Could this be included with the pipewire permission, or maybe added separately in the GUI?

Thanks.

**Comment by igo95862** [comment]
Hello @odomingao

> is needed for pipewire screensharing to work with browsers and obs

The pipewire socket (that the `[pipewire]` service provides) is not actually required to screen share. Its the portal access that is required. Pipewire is simply an implementation of the portal is not directly related to it.

I plan on adding a better access control to the portal in the future release.
