### ISSUE TITLE
Suddenly symlinks are a problem?

### ISSUE THREAD

**Issue by Baerbeisser** [igo95862/bubblejail#120]
### Description

I have my Steam folder on my huge Games disk, thus a symlink as bubblejail-home/.local/share/Steam pointing to it.
I didn't play steam games for about two months, and now mkdir complains about not being able to create the folder, it exists already, which aborts the whole process.
I deleted the symlink , a new Steam folder got created, launching Steam in the jail works repeatedly. If i replace the folder with the symlink, same error again.
My guess is, a check got lost in a recent update?

**Comment by igo95862** [comment]
Hello @Baerbeisser 

There should not have been any changes. Maybe it is bubblewrap that got changed but bubblejail did not have any changes.

By the way, what is the error you are experiencing?

**Comment by Baerbeisser** [comment]
Right, sorry.
Version:  AUR-git 0.9.0.r2.gdb764fa

```
LC_ALL=C bubblejail run -- steam /usr/bin/steam-runtime
Sandboxed PID: 16656
Bubblewrap started. PID: <Process 16655>
Started unix server
bin_steam.sh[2]: Setting up Steam content in /home/dani/.local/share/Steam
mkdir: das Verzeichnis „/home/dani/.local/share/Steam“ kann nicht angelegt werden: Die Datei existiert bereits
No children found. Terminating.
Terminated
Bubblewrap terminated
```
Now that i look again, bin_steam.sh is from Steam? But can't find that script.

**Comment by igo95862** [comment]
`bin_steam.sh[2]:` means that it is the steam script that fails.

Looks like it tries to call the `mkdir` on `/home/dani/.local/share/Steam` and fails because it already exists? (`Die Datei existiert bereits`)

Maybe the Steam tries to check if `/home/dani/.local/share/Steam` is a directory but because it is a symlink it thinks that it does not exist and tries to create it again which fails?

**Comment by igo95862** [comment]
The bubblejail successfully initialized but it is Steam that fails. Maybe they changed how `.local/share/Steam` is checked if it exists.

**Comment by Baerbeisser** [comment]
No, like i said, Steam native launches fine with `$HOME/.local/Steam` as symlink to my gamedir.
Only Steam in Bubblewrap has a problem with Steam directory as symlink.

**Comment by igo95862** [comment]
Why is it raising an error that directory already exists then?

You can launch a terminal inside sandbox using `bubblejail run -- steam alacritty` (replace `alacritty` with your choice of terminal) and see what is visible from inside sandbox.

**Comment by Baerbeisser** [comment]
Yeah, `/usr/sbin/steam` fails in Bubblewrap on mkdir, while native runs. Both having Steam directory as symlink.

But how?

**Comment by igo95862** [comment]
You can try analyzing syscalls using `strace`.

**Comment by Baerbeisser** [comment]
Well, fine. Any case, it's not a Bubblejail issue, let's close this.

**Comment by igo95862** [comment]
By the way I usually use the `[root_share]` and add a new Steam library to put games on another hard drive. This way only the Steam's internal files are placed on my home drive but they are usually not that large.
