### ISSUE TITLE
Meson Build Error: Project keyword argument 'default options' is supposedly wrong type

### ISSUE THREAD

**Issue by harisqazi1** [igo95862/bubblejail#129]
### Output of `bubblejail --version`

N/A

### Your distro name and version

Pop!_OS 22.04 LTS x86_64

### Description

I am getting the following error when attempting to build bubblejail with Meson (`meson setup build`):

```
The Meson build system
Version: 0.61.2
Source dir: /home/user/Desktop/bubblejail
Build dir: /home/user/Desktop/bubblejail/build
Build type: native build

meson.build:3:0: ERROR: project keyword argument 'default_options' was of type array[dict] but should have been array[str | IncludeDirs]

A full log can be found at /home/user/Desktop/bubblejail/build/meson-logs/meson-log.txt
```

Full log output:

```
Build started at 2024-09-16T18:05:24.030645
Main binary: /usr/bin/python3
Build Options: 
Python system: Linux
The Meson build system
Version: 0.61.2
Source dir: /home/user/Desktop/bubblejail
Build dir: /home/user/Desktop/bubblejail/build
Build type: native build

meson.build:3:0: ERROR: project keyword argument 'default_options' was of type array[dict] but should have been array[str | IncludeDirs]
```
I tried to look this issue online, but was not able to find a proper solution for this issue. In addition, the only locations "default_options" was mentioned was in the following (output from `rg -aFiN "default_options"`):

```
meson.build
    default_options : {
    subproject('python-lxns', default_options : {'use_limited_api': true})

CHANGELOG.md
  you can either patch `meson.build` or use `meson rewrite kwargs delete project / default_options ""`
```

Any recommendations on how to solve this build issue?

**Comment by rusty-snake** [comment]
Maybe update your meson? 0.61 is 2.5 years old.

**Comment by igo95862** [comment]
Hello @harisqazi1 

I am developing against a very recent meson versions. It looks like passing the dictionary to the `project()` has been added in meson 1.2.0

https://mesonbuild.com/Reference-manual_functions.html#project

You can patch the project call to use the list of strings in the format of `["key=value"]` or use more recent meson version.

**Comment by rusty-snake** [comment]
@igo95862 did you considered to add a `meson_version` to the project call? It will make clear which version is required to users and warn you if you start using a feature added in a more recent version.

**Comment by igo95862** [comment]
I thought about it but I want to use the latest meson features. The Python support has been significantly enchanced in the latest versions. For example, `python.bytecompile` was added in 1.2.0 and `python.allow_limited_api` in 1.3.0

**Comment by rusty-snake** [comment]
Then set it to `>=1.3.0` and bump it if necessary. Because the error message it gives is very clear:

```
meson.build:6:17: ERROR: Meson version is 1.4.1 but project requires >=1.5
```

compared to something like `meson.build:3:0: ERROR: project keyword argument 'default_options' was of type array[dict] but should have been array[str | IncludeDirs]` which could also be a bug in bubblejails meson.build.

**Comment by harisqazi1** [comment]
> Maybe update your meson? 0.61 is 2.5 years old.

Thanks for pointing this out. I downloaded meson with pip3 so it might've been older in their repo. I got the newer copy from https://github.com/mesonbuild/meson.git and was using it for the rest of the commands. I then ran into another issue. After the install (`sudo meson install`), when I run Bubblejail, I get the following error:

```python
Traceback (most recent call last):
  File "/usr/local/bin/bubblejail", line 18, in <module>
    from bubblejail.bubblejail_cli import bubblejail_main
  File "/usr/local/lib/bubblejail/python-packages/bubblejail/bubblejail_cli.py", line 12, in <module>
    from .bubblejail_directories import BubblejailDirectories
  File "/usr/local/lib/bubblejail/python-packages/bubblejail/bubblejail_directories.py", line 9, in <module>
    from tomllib import load as toml_load
ModuleNotFoundError: No module named 'tomllib'
```
I have tried running `pip3 install toml` and `pip3 install tomllib`, but no luck. I also did look online to mitigate this issue as well, with no luck there either. I can create another issue for this if needed. Are there any plans in the future to have a .dpkg or appimage for Bubblejail?

**Comment by rusty-snake** [comment]
> I have tried running pip3 install toml and pip3 install tomllib, but no luck

Instead of guessing package names (and installing some typo-squatting malware), you should really read documentation.
To be provocative, with such operating mistakes no sandbox can help you.

> No module named 'tomllib'

Here are the requirements: https://github.com/igo95862/bubblejail?tab=readme-ov-file#runtime-requirements
Among others: Python 3 (***>= 3.11***)

> sudo meson install

Don't run builds as root

**Comment by igo95862** [comment]
I think Ubuntu 20.24 has Python 3.12 so once new PopOs version comes out it should be compatible.

**Comment by rusty-snake** [comment]
s/20.24/24.04/

**Comment by igo95862** [comment]
I added a minimum meson version specifier in deea5261f29f7d5598efc72b367512deb03e55d8. It is also possible to add a Python version check.

**Comment by igo95862** [comment]
@harisqazi1 you can try running some older version of bubblejail. I believe 0.8.3 did not make use of those meson features and supported `tomli` third party library instead of `tomllib` from Python 3.11.

**Comment by harisqazi1** [comment]
> Don't run builds as root

The README literally says to do so:

```markdown
#### Using meson to install

1. Run `meson setup build` to setup build directory
1. Switch to build directory `cd build`
1. Compile `meson compile`
1. Install `sudo meson install` <--
```

If sudo/root is not needed, would you be able to remove it from the README to prevent someone else from running it as sudo/root? Thanks.

@igo95862 Thanks for your recommendation! The systems I use are not rolling-release, so I might come back if I do end up using a system as such. The project seems focused on bleeding edge builds for Arch, so it might not be the best fit for my usage. Regardless, I appreciate your guys' help on this issue. Closing this issue as the original issue was solved.

**Comment by igo95862** [comment]
> If sudo/root is not needed, would you be able to remove it from the README to prevent someone else from running it as sudo/root?

`meson install` is intended to be run with sudo as it installs in to the `/usr/bin/local` directory. However, using `/usr/bin/local` to bypass the distro packaging is not very elegant solution. I have plans to experiment with `pipx` so that users can do unprivileged install.

**Comment by rusty-snake** [comment]
> meson install is intended to be run with sudo as it installs in to the /usr/bin/local directory. 

`meson install` will (re)build all targets that are considered outdated, hence if you run it as root you should add `--no-rebuild`. However, `meson install` can also be used to (re)build and then install if it was started as normal user. It will then use sudo/polkit for the install code.

**Comment by igo95862** [comment]
Apparently since meson 1.1.0 the meson will drop the privileges on its own to rebuild the targets: https://mesonbuild.com/Release-notes-for-1-1-0.html#sudo-meson-install-now-drops-privileges-when-rebuilding-targets

**Comment by rusty-snake** [comment]
Good to hear. From a security perspective this looks much better - though it's still "drop for unwanted" rather than "raise for required".  However it can cause build problems because of changed environment, etc. So I will stick to my recommendation to avoid debugging strange things.
