### ISSUE TITLE
Random error with dbus_session_proxy

### ISSUE THREAD

**Issue by donob4n** [igo95862/bubblejail#13]
Hi,

I feel that since Alpinelinux migrated to python3.10 I'm experiecing some errors like:
`b"bwrap: Can't find source path /run/user/1000/bubblejail/qutetor/dbus_session_proxy: No such file or directory\n"
`

I tried to fix it and I feel that the problem is due the async behaviour of runtime dir creation. If try to run some app it fails like 3 o 4 times and finally works. I think that some % of the time brwap is launched before the runtime_dir has been created. Could it be the case? Is really need to use an async method for doing this?

**Comment by igo95862** [comment]
Very strange. I am running Python 3.10 on Arch Linux and never had such issue.

Maybe there is a difference in how sockets are created between Musl and Glibc? (assuming in musl socket creating is an async operation but sync in glibc)

**Comment by igo95862** [comment]
Try inserting 

```python
from time import sleep
sleep(1)
```

Somewhere here: https://github.com/igo95862/bubblejail/blob/2cf8cd937bc4900d1af7571f99886ae19df3d1fe/bubblejail/bubblejail_instance.py#L317

**Comment by donob4n** [comment]
With the sleep(1) it works perfect.

**Comment by donob4n** [comment]
> Very strange. I am running Python 3.10 on Arch Linux and never had such issue.
> 
> Maybe there is a difference in how sockets are binded between Musl and Glibc? (assuming in musl socket binding is an async operation but sync in glibc)

Looking at musl source code it seems very unlikely but I'm not sure.

**Comment by igo95862** [comment]
What about [os.sync()](https://docs.python.org/3/library/os.html#os.sync) ? Is the `/run` directory on Alpine Linux a tmpfs?

**Comment by donob4n** [comment]
os.sync() also seems to work fine.

Yes both '/run' and '/run/user/1000' are tmpfs mounts.

**Comment by igo95862** [comment]
I am a very baffled by this and can't think of quick solution. (especially because I can't replicate it) I can't find anything useful online.

`os.sync()` will force all disks to flush so I really want to avoid calling that. I wonder if something like `self.runtime_dir.stat()` will also cause it to sync up but for specific directory.

**Comment by donob4n** [comment]
Well I added some debug and python execution seems well ordered:

```
Connecting dbus session
Connected dbus session
<socket.socket fd=13, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/run/user/1000/bubblejail/qutetor/dbus_session_proxy>
Connecting dbus system
Connected dbus system
<socket.socket fd=14, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/run/user/1000/bubblejail/qutetor/dbus_system_proxy>
FINISH
b"bwrap: Can't find source path /run/user/1000/bubblejail/qutetor/dbus_session_proxy: No such file or directory\n"
```

I don't know if some mount option could have some relation:
```
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,relatime,inode64)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=3259576k,nr_inodes=814894,mode=700,uid=1000,gid=1000,inode64)

```

**Comment by donob4n** [comment]
After adding:

` system("ls /run/user/1000/bubblejail/qutetor/")`

It works fine. It seems that 'ls' forces the sync or something like it.

**Comment by donob4n** [comment]
Interesting, I modified bwrap_args for run 'ls' with the same async create_subprocess_exec than bwrap. It worked fine for many executions:
```
Connecting dbus session
Connected dbus session
<socket.socket fd=13, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/run/user/1000/bubblejail/qutetor/dbus_session_proxy>
Connecting dbus system
Connected dbus system
<socket.socket fd=14, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/run/user/1000/bubblejail/qutetor/dbus_system_proxy>
LOL
['/bin/ls', '/run/user/1000/bubblejail/qutetor']
b'dbus_session_proxy\n'
b'dbus_system_proxy\n'
b'helper\n'

```
But then I restored it to original and next execution failed:

```
Connecting dbus session
Connected dbus session
<socket.socket fd=13, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/run/user/1000/bubblejail/qutetor/dbus_session_proxy>
Connecting dbus system
Connected dbus system
<socket.socket fd=14, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/run/user/1000/bubblejail/qutetor/dbus_system_proxy>
LOL
['/usr/bin/bwrap', '--args', '15', '/usr/lib/bubblejail/bubblejail-helper', 'qutebrowser']
b"bwrap: Can't find source path /run/user/1000/bubblejail/qutetor/dbus_session_proxy: No such file or directory\n"
```

Maybe the problem is that bwrap is using some IO layer that ignores the FS cache?

**Comment by donob4n** [comment]
Related: https://github.com/containers/bubblewrap/issues/387

Maybe it finally has some relation with musl.

**Comment by igo95862** [comment]
> Related: [containers/bubblewrap#387](https://github.com/containers/bubblewrap/issues/387)
> 
> Maybe it finally has some relation with musl.

Definitely feels like it. Maybe you can ask Alpine Linux or musl forums or mailing lists?

**Comment by igo95862** [comment]
> After adding:
> 
> ` system("ls /run/user/1000/bubblejail/qutetor/")`
> 
> It works fine. It seems that 'ls' forces the sync or something like it.

I might add this hack in case the bubblejail gets launched on system with Musl. There is [platform.libc_ver](https://docs.python.org/3/library/platform.html#platform.libc_ver) call to get the libc name.

**Comment by ericonr** [comment]
Please don't do that...

As I was asking donob4n on IRC, it would be nice to check both an strace and what happens when the `bwrap` call is started only after the function that creates sockets returns (truly returns). You can't be sure about scheduling between async tasks unless it's explicit, and I wouldn't be surprised if the time for `os.sync()` or `system()` causes them to "sync up".

And `os.sync()` shouldn't affect what files are visible to any application.

**Comment by donob4n** [comment]
`strace` would be helpful but unfortantely I can't reproduce the issue with it. It seems that the delay that it adds is enough for avoiding it.

It's strange that bubblejail has been running perfectly for months. I feel that I started to experiment this problem with python 3.10 upgrade, since there are some suspects on musl I checked it in the log but there is no upgrade since Sep 22 (which was adding a patch for qsort_r()). The python upgrade was on Dec 15. Unfortantely dowgroading python is not trivial.

**Comment by igo95862** [comment]
It might also be a kernel bug. If you look at both glibc and musl source code the bind function is really simple. (basically only does a syscall)

**Comment by donob4n** [comment]
Just tested latest 5.15 and 5.16. Same problem. Maybe I should try to downgrade it.

**Comment by igo95862** [comment]
I might try a VM with a fresh install on Alpine Linux.

**Comment by donob4n** [comment]
Alpine 3.15 uses python3.9, maybe you could try to slowly upgrade things to edge. However I'm worry that the slight overhead that virtualization adds avoids the race condition.

**Comment by donob4n** [comment]
I added some debug to bwrap and noticed that it fails before trying to bind the mount.

It dies here: https://github.com/containers/bubblewrap/blob/master/bubblewrap.c#L1437

**Comment by igo95862** [comment]
Might be an issue with `realpath` in musl. Not sure... Attaching a debugger will probably introduce too much latency and make bug disappear.

**Comment by donob4n** [comment]
We digged into the execution path until reach a readlink() call that says ENOENT. Or the kernel is lying or there is a problem with paralell execution of init and brwap lauching. I read some doc about async context and I don't think that currently there are any aguarantees of brwap being executed after the socket is ready:

https://github.com/igo95862/bubblejail/blob/2cf8cd937bc4900d1af7571f99886ae19df3d1fe/bubblejail/bubblejail_instance.py#L317

I would like to try something for doing it but I don't know very much about async python. A solution could be add some event/signal which beings triggered after the socket is created and just wait for it before starting the bwrap process.

Maybe you know another wait of adding some kind of: 'await init.wait()' there.

**Comment by igo95862** [comment]
It is also possible to add the signaling mechanism to xdg-dbus-proxy but that will take much more work and time.

**Comment by donob4n** [comment]
Well I can confirm that the problem is caused by 'xdg-dbus-proxy', if I remove it the problem dissappears.

I wonder if 'xdg-dbus-proxy' does something to the socket and for a short while it dissapears, maybe it acts differently on musl and glibc.

**Comment by igo95862** [comment]
> Well I can confirm that the problem is caused by 'xdg-dbus-proxy', if I remove it the problem dissappears.
> 
> I wonder if 'xdg-dbus-proxy' does something to the socket and for a short while it dissapears, maybe it acts differently on musl and glibc.

I think it actually deletes whatever was on the socket path and just creates a new one:

https://github.com/flatpak/xdg-dbus-proxy/blob/15d2803039b1964dc95112d6d1624a291d338c4e/flatpak-proxy.c#L2822

When I first added the dbus proxies I kind experimented until something worked. But my assumption was totaly wrong.

I can just delete entire block where sockets are created and everything will still work fine on my end.

I think with glibc the programs start much slower to the point that xdg-dbus-proxy manages to create sockets in time before bwrap starts.

```patch
diff --git a/bubblejail/bubblejail_instance.py b/bubblejail/bubblejail_instance.py
index d2642dc..d4a3c8e 100644
--- a/bubblejail/bubblejail_instance.py
+++ b/bubblejail/bubblejail_instance.py
@@ -584,16 +584,6 @@ class BubblejailInit:
         # Create helper directory
         self.helper_runtime_dir.mkdir(mode=0o700)
 
-        # Dbus session proxy
-
-        self.dbus_session_socket = socket(AF_UNIX, SOCK_STREAM)
-        self.dbus_session_socket.bind(
-            str(self.dbus_session_socket_path))
-
-        self.dbus_system_socket = socket(AF_UNIX, SOCK_STREAM)
-        self.dbus_system_socket.bind(
-            str(self.dbus_system_socket_path))
-
         # Pylint does not recognize *args for some reason
         # pylint: disable=E1120
         self.dbus_proxy_process = await create_subprocess_exec(
```

**Comment by igo95862** [comment]
I think I will either look in to inotify (but I really don't want to pull another dependency) or look in to whatever flatpak is doing.

**Comment by igo95862** [comment]
Ok. I think I have it figured out.

There is an *undocumented* feature there the xdg-dbus-proxy writes to the passed file descriptor. 

https://github.com/flatpak/xdg-dbus-proxy/blob/15d2803039b1964dc95112d6d1624a291d338c4e/dbus-proxy.c#L417

Should be trivial to use. I will write a fix this weekend.

**Comment by donob4n** [comment]
@ericonr commented on IRC that there is an argument on xdg-dbus-proxy for notify when proxies are ready:
```
       --fd=FD
           Write to FD when the proxies are ready, and stop when it is closed.
```

**Comment by igo95862** [comment]
> @ericonr commented on IRC that there is an argument on xdg-dbus-proxy for notify when proxies are ready:
> 
> ```
>        --fd=FD
>            Write to FD when the proxies are ready, and stop when it is closed.
> ```

Yeah, but the `--help` command will only talks about stopping when it is closed.

**Comment by igo95862** [comment]
@donob4n I added cfb7c4ef854fc0edbb8d9f489b43d17ed2d97d34 to master which should now properly wait for proxy to initialize. Would you mind testing it?

**Comment by donob4n** [comment]
I'm testing it. Seems fine! I did many reopenings without failure.

**Comment by donob4n** [comment]
Do you expect to release a new version for this?

**Comment by igo95862** [comment]
Yes but I will add a few fixes as well.

**Comment by igo95862** [comment]
@donob4n 0.4.4 has been released

**Comment by donob4n** [comment]
Great!! I will upgrade it on alpinelinux, I'm closing this. Thanks for your fast attention!

**Comment by igo95862** [comment]
By the way I am planing on using my D-Bus library in-place of homebrew pseudo JSON RPC I currently use: https://github.com/python-sdbus/python-sdbus

The issue it is using `libsystemd` which has dependency on `glibc`. Not sure if it will be possible to run on Alpine Linux. I will probably add a degraded mode if the D-Bus fails to initialize...

**Comment by donob4n** [comment]
Oh Alpine and systemd are not good friends hehe

**Comment by ericonr** [comment]
@igo95862 if it only uses the dbus side of things, it can probably be fixed to use libelogind or basu. I leave that to interested parties, however.

**Comment by igo95862** [comment]
> @igo95862 if it only uses the dbus side of things, it can probably be adapted to use libelogind or basu. I leave that to interested parties, however.

I did not know that libelogind implements the sd-bus API. I will look in to it.
