### ISSUE TITLE
Fedora Firefox not detected

### ISSUE THREAD

**Issue by boredsquirrel** [igo95862/bubblejail#130]
### Output of `bubblejail --version`

0.9.0

### Your distro name and version

Fedora Kinoite 40

### Description

org.mozilla.firefox.desktop is not detected as firefox and I cannot proceed.

**Comment by boredsquirrel** [comment]
I also thought of Zen and Floorp, but both dont have an RPM repo yet

**Comment by igo95862** [comment]
I created 1ba9cc64a5de62d49aba40d78c260f8dd3407ee4 which adds the Fedora's unique desktop entry name. @boredsquirrel can you give it a test?

I saw your PR adds some Firefox forks destop entries, however, the current system is not well suited for this. I do plan to explore adding forks to the profiles in the future.

**Comment by boredsquirrel** [comment]
Thanks I already saw that!

I need to do some PRs on the packaging repos and wait for COPR, or build it myself which I currently have no time for.

**Comment by igo95862** [comment]
Fixed in 0.9.3
