### ISSUE TITLE
Steam d-bus name error

### ISSUE THREAD

**Issue by consolation548** [igo95862/bubblejail#135]
### Output of `bubblejail --version`

0.92

### Your distro name and version

6.6.47-gentoo-x86_64

### Description

steam, apparently, requires `com.steampowered.*` d-bus name to be acquired.
otherwise, on launch it produces errors:

`steam-runtime-launcher-service[321]: E: Unable to acquire bus name "com.steampowered.PressureVessel.LaunchAlongsideSteam"
Steam Runtime Launch Service: steam-runtime-launcher-service pid 321 exited
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 396
steam-runtime-launcher-service[396]: E: Unable to acquire bus name "com.steampowered.PressureVessel.LaunchAlongsideSteam"
Steam Runtime Launch Service: steam-runtime-launcher-service pid 396 exited
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 403
steam-runtime-launcher-service[403]: E: Unable to acquire bus name "com.steampowered.PressureVessel.LaunchAlongsideSteam"
Steam Runtime Launch Service: steam-runtime-launcher-service pid 403 exited
Steam Runtime Launch Service: steam-runtime-launcher-service keeps crashing on startup, disabling
Reaped:  138  Exit code:  0
`

**Comment by igo95862** [comment]
Hello @consolation548 

Can you try adding the

```
dbus_name = "com.steampowered.*"
```

to the `[common]` section of your instance config?

**Comment by igo95862** [comment]
Hmmm... So Steam does produce the errors like this: 

```
steam-runtime-launcher-service[514]: E: Unable to acquire bus name "com.steampowered.PressureVessel.LaunchAlongsideSteam
```

However, I am not entirely sure what it breaks? Stream still seems to work fine.

**Comment by igo95862** [comment]
Looks like Flatpak also added the `com.steampowered.*` D-Bus domain name to the Steam: https://github.com/flathub/com.valvesoftware.Steam/pull/1200

**Comment by igo95862** [comment]
Added in fedc7b796cd8b9632e55edeff27c453a1ce63f16.
