### ISSUE TITLE
Apps dont see their bubblejail home and thus use the user home

### ISSUE THREAD

**Issue by boredsquirrel** [igo95862/bubblejail#142]
### Output of `bubblejail --version`

0.9.3

### Your distro name and version

Fedora 40 Kinoite

### Description

*This may be just a cosmetic issue with folders being shown at 2 places.*

I am using a pretty vanilla Firefox config, just enabled pipewire and v4linux.

It launches fine, but pressing Ctrl+O (Filepicker) shows me my user home directory, with the download folder inside.

Trying to go to `.local/share/` doesnt display the directory `bubblejail`. This may be a security measurement? But it prevents me from using the internal home directory entirely.

I thus cannot find `~/.local/share/bubblejail/instances/INTANCE-NAME/home` in the GTK filepicker.

I closed Firefox-bubble and changed the config
- removed Download folder access
- added access to `~/.local/share/bubblejail/instances/firefox-vanilla/home` 

started it again, now it could see it's home folder normally

then I closed it again and added the `Downloads` folder back, the config now is

```
[common]
executable_name = "/usr/bin/firefox"
share_local_time = false
filter_disk_sync = false
dbus_name = "org.mozilla.*"

[wayland]

[network]

[pulse_audio]

[home_share]
home_paths = [
    ".local/share/bubblejail/instances/firefox-vanilla/home",
    "Downloads",
]

[direct_rendering]
enable_aco = false

[notify]

[pipewire]

[v4l]
```

the GTK filepicker shows me an entirely sandboxed filesystem including root, I have no idea how I could now access the downloads again. It tells me I am in `/var/home/user` but the "Downloads" folder only contains a single file that I placed in the bubblejail home Downloads folder.

I tried a workaround, symlinking my downloads folder into the bubblejail downloads folder, which results in an error launching the app

```
bubblejail run firefox-vanilla firefox
Sandboxed PID: 1759042
Bubblewrap started. PID: <Process 1759041>
bwrap: Can't bind mount /oldroot/var/home/user/Downloads on /newroot/var/home/user/Downloads: Unable to mount source on destination: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/bubblejail", line 20, in <module>
    bubblejail_main()
  File "/usr/lib64/bubblejail/python-packages/bubblejail/bubblejail_cli.py", line 232, in bubblejail_main
    func(**args_dict)
  File "/usr/lib64/bubblejail/python-packages/bubblejail/bubblejail_cli.py", line 100, in run_bjail
    async_run(
  File "/usr/lib64/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib64/bubblejail/python-packages/bubblejail/bubblejail_instance.py", line 241, in async_run_init
    raise BubblewrapRunError(
bubblejail.exceptions.BubblewrapRunError: Bubblewrap failed. Try running bubblejail in terminal to see the exact error.
```

hardlinking directories is not possible

I just cut and pasted my normal downloads folder into the bubblejail home and linked it into my home. This may cause other issues in the future

**Comment by igo95862** [comment]
> It launches fine, but pressing Ctrl+O (Filepicker) shows me my user home directory, with the download folder inside.

Do you mean the file picker launches outside the sandbox? Is it using the portal?

**Comment by boredsquirrel** [comment]
This is just a confusing cosmetic issue

This works differently than with flatpaks

when allowing Downloads, the GTK filepicker launches in the sandboxed home, and has the unsandboxed "Downloads" mounted there as if it was a normal directory. All other files are actually the ones in `~/.local/share/bubblejail/instances/instance-name/home/`

This is not an issue but a bit confusing, could need documentation.
