### ISSUE TITLE
secure global Flatpak configs to protect bubblejail home

### ISSUE THREAD

**Issue by boredsquirrel** [igo95862/bubblejail#143]
### Description

Afaik bubblejail protects it's home from other bubblejailed applications.

To complete this, Flatpak apps must not access the bubblejail directories either.

This can be accomplished like this:

```
cat >> ~/.local/share/flatpak/overrides/global <<EOF
[Context]
filesystems=!~/.local;!~/.bashrc;!~/.bash_env;!~/.bash_profile;!~/.bash_login;!~/.bash_logout;!~/.config;!~/.zshrc;!~/.zshenv;!~/.zprofile;!~/.zlogin;!~/.zlogout;!~/.local/bin;!~/.bin
EOF
```

This blocks all flatpak apps from changing their own configurations, and from accessing the bubblejail homes or configs.

Or the more complete file that I use, to block pulseaudio, x11 and ipc to prevent apps sniffing each other.

```
cat >> ~/.local/share/flatpak/overrides/global <<EOF
[Context]
filesystems=xdg-run/pipewire-0:ro;!~/.local/share/flatpak/overrides;!~/.ssh;!~/.gnupg;!~/.local/share/bubblejail;!~/.bashrc;!~/.bash_env;~/.bash_profile;~/.bash_login;~/.bash_logout;!~/.config;~/.zshrc;~/.zsh_login;~/.zprofile;~/.zlogin;~/.zlogout;~/.local/bin
sockets=!x11;!pulseaudio;wayland;
shared=!ipc;

[Environment]
QT_QPA_PLATFORM=wayland
ELECTRON_OZONE_PLATFORM_HINT=auto
EOF
```

https://github.com/flatpak/flatpak/issues/6003

**Comment by igo95862** [comment]
Interesting but I am not sure about messing with other applications settings.

Also wouldn't it only be relevant for flatpak applications that have complete access to home file system?

**Comment by rusty-snake** [comment]
My two cents about this,

- you need to also update firejail, sydbox, systemd, ... sandboxes otherwise it is an incomplete fix => use less theatre
- flatpaks with `home` or `host` access can also write to `.bashrc`, `.config/systemd`, ...

**Comment by boredsquirrel** [comment]
hi there

yes this is only relevant for the apps that have access there.

Just because the Linux desktop is not perfectly secure, I dont agree with the stance that we shouldn't try to fix this.

Instead, I would add all the paths you mentioned and a few more.
