### ISSUE TITLE
Error when compiling meson

### ISSUE THREAD

**Issue by ADHyperActive** [igo95862/bubblejail#149]
### Output of `bubblejail --version`

N/A (Issue relates to installation)

### Your distro name and version

Zorin OS Core 17.2

### Description

When trying to configure, Meson gives this output:

Build started at 2024-12-11T17:30:38.432460
Main binary: /usr/bin/python3
Build Options: 
Python system: Linux
The Meson build system
Version: 0.61.2
Source dir: /home/[username]/Downloads/bubblejail-master
Build dir: /home/[username]/Downloads/bubblejail-master/build
Build type: native build

meson.build:3:0: ERROR: project keyword argument 'default_options' was of type array[dict] but should have been array[str | IncludeDirs]

**Comment by rusty-snake** [comment]
> Version: 0.61.2

Whatever Zorin OS Core 17.2 is but it looks like it has a very outdated meson version.

https://github.com/igo95862/bubblejail/blob/9777f9ccf9b3bb370def2479d19d489801007ff2/meson.build#L5

Try to install meson via pip.

**Comment by igo95862** [comment]
Hello @ADHyperActive 

Your meson version is too low. The minimum required version is 1.3.0 as of deea5261f29f7d5598efc72b367512deb03e55d8.

**Comment by rusty-snake** [comment]
Duplicated of #129

**Comment by igo95862** [comment]
Also you are probably trying to compile some old bubblejail version. Since version 0.9.3 there should be a minimum version requirement in the `meson.build`.
