### ISSUE TITLE
Add a --version option?

### ISSUE THREAD

**Issue by chocolateboy** [igo95862/bubblejail#18]
It's [customary](https://stackoverflow.com/a/54036429) for command-line tools to have a `--version` (and/or `-v` or `-V`) option to display the version (and exit). In the case of the [bubblejail](https://aur.archlinux.org/packages/bubblejail) package on AUR, it can be gleaned from the package database (though it differs (0.5.1) from the version in the [README](https://github.com/igo95862/bubblejail#packages) (0.5.0)), but [bubblejail-git](https://aur.archlinux.org/packages/bubblejail-git) only reveals an unrelated revision number, so the trivial task of finding out which version is installed ends up requiring a non-trivial amount of detective work.

## Test

```
$ bubblejail --version
```

## Expected

```
0.5.1
```

## Actual

```
usage: bubblejail [-h] {run,create,list,edit,generate-desktop-entry} ...
bubblejail: error: the following arguments are required: {run,create,list,edit,generate-desktop-entry}
```

**Comment by igo95862** [comment]
Definitely doable. I will investigate best way to add it.

> it can be gleaned from the package database (though it differs (0.5.1) from the version in the README (0.5.0)),

No idea why that happened. Version 0.5.1 is on AUR but repology widget did not update.
