### ISSUE TITLE
How to use browserpass?

### ISSUE THREAD

**Issue by bratekarate** [igo95862/bubblejail#20]
I am using browserpass for firefox. I managed to get the extension to open without error with the following .toml configuration:

```
[home_share]
home_paths = [
    "Downloads",
    ".password-store",
]
```
However, of course it fails if I try to decrypt a password. It cannot access gpg. So I also allowed access to .gnupg:

```
[home_share]
home_paths = [
    "Downloads",
    ".password-store",
    ".gnupg",
]

```
Now I don't get an error anymore when  decrypting, but it seems to create a new instance of gpg-agent and scdaemon. I use a smart card, so it cannot access it because my host scdaemon already has it locked. 

Is there any way to share the same scdaemon and gpg-agent with the sandbox? I tried the following, just as an idea, without much knowledge:

```
[root_share]
paths = [
    "/run/user/1000/gnupg",
]
```
But it made no difference. It asks me to insert the smartcard inside the sandbox, outside it works. Any ideas?

**Comment by igo95862** [comment]
> Is there any way to share the same scdaemon and gpg-agent with the sandbox?

I think passing the gpg-agent socket should work but there might be an issue if gpg tries to lookup the process in `/proc` directory. I am not very familiar with gpg.

If you want to debug this issue I would recommend using the `--debug-shell` option to spawn a shell in the terminal and see if gpg would be able to use socket. (there is also `--debug-bwrap-args` to add additional argument to bwrap)

**Comment by bratekarate** [comment]
Strangely it works now with exactly the same configuration as mentioned above. May have been another issue with pcscd and gnupg. Sometimes the daemon prevents GPG from working with the yubikey and the daemon needs to be restarted. Not entirely sure how to reproduce, but the setup above is indeed correct.
