### ISSUE TITLE
Opera doesn't works

### ISSUE THREAD

**Issue by Nonie689** [igo95862/bubblejail#22]
this is my conf...

[common]
dbus_name = ""
executable_name = [
    "/usr/bin/opera",
    "--enable-features=UseOzonePlatform",
    "--ozone-platform=wayland",
    "%u",
]
filter_disk_sync = true
share_local_time = true

[wayland]

[network]

[pulse_audio]

[home_share]
home_paths = [
    "Downloads",
    ".config/",
]

[direct_rendering]
enable_aco = true

[notify]

[pipewire]

**Comment by rusty-snake** [comment]
`%u` is desktop file syntax, see https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables.

**Comment by igo95862** [comment]
> `%u` is desktop file syntax, see https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables.

I know but it should not get in to bubblejail config file. They are not interpreted in any way.

**Comment by igo95862** [comment]
@Nonie689 any updates?

I would recommend using the new version 0.6.0, recreate the instance and explicitly generate the opera desktop entry.

`bubblejail create --profile generic  opera `
`bubblejail generate-desktop-entry --desktop-entry /usr/share/applications/opera.desktop opera`

(approximate names, I don't have opera installed)
