### ISSUE TITLE
librewolf link opening fails

### ISSUE THREAD

**Issue by Nonie689** [igo95862/bubblejail#23]
bubblejail run librewolf www.example.org

this is my conf:

[common]
dbus_name = ""
executable_name = [
    "/usr/bin/librewolf",
    "%U",
]
filter_disk_sync = true
share_local_time = true

[wayland]

[network]

[pulse_audio]

[home_share]
home_paths = [
    "Downloads/",
    ".librewolf",
]

[direct_rendering]
enable_aco = true

[systray]

[pipewire]

**Comment by igo95862** [comment]
Please run the shell inside the snadbox (`bubblejail run --debug-shell librewolf`) and run librewolf manually `/usr/bin/librewolf`. Post any error logs you encounter.

```
executable_name = [
"/usr/bin/librewolf",
"%U",
]
```

The `%U` part is definitely wrong. How did you get it?

**Comment by Nonie689** [comment]
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<BubblejailHelper.client_handler() done, defined at /usr/lib/bubblejail/python_packages/bubblejail/bubblejail_helper.py:353> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_helper.py", line 375, in client_handler
    run_stdout = await self.run_command(
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_helper.py", line 341, in run_command
    p = await create_subprocess_exec(
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 799, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'https://www.google.de'

**Comment by igo95862** [comment]
Looks like you are passing `'https://www.google.de'` as the executable name.

What is your command line. It should probably be something like `bubblejail run librewolf librewolf 'https://www.google.de'`. Note that `librewolf` is repeated twice. First is the name of the instance and second is the executable name. You can also replace second one with `/usr/bin/librewolf`.

**Comment by igo95862** [comment]
@Nonie689 any updates.

I would recommend using the new version 0.6.0, recreate the instance and explicitly generate the librewolf desktop entry.

`bubblejail create --profile generic  librewolf `
`bubblejail generate-desktop-entry --desktop-entry /usr/share/applications/librewolf.desktop librewolf`
