### ISSUE TITLE
f.write(d) TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by bencejuhaasz** [igo95862/bubblejail#27]
``` 
File "/usr/lib/python3.10/site-packages/toml/encoder.py", line 30, in dump
    f.write(d)
TypeError: a bytes-like object is required, not 'str'
```
Somehow you are giving the file in the wrong format to the toml encoder. Adding `.encode()` to variable `d` fixes it. Can you do this in your code, so it gets to the python package the right way ?

**Comment by igo95862** [comment]
Are you using old `toml` package?

I switched to `tomli`/`toml_w` package because `toml` is abandoned. I think there could be an issue with `toml` only taking string but `tomli` uses bytes.

**Comment by bencejuhaasz** [comment]
That might be the case. Meson was still checking for the old `toml`, so I installed that.

**Comment by igo95862** [comment]
> That might be the case. Meson was still checking for the old `toml`, so I installed that.

In my build files?

**Comment by igo95862** [comment]
@bencejuhaasz any luck with installing `tomli`/`tomli_w`?

**Comment by bencejuhaasz** [comment]
Nope, it only works with python3-toml and the change in the code.

**Comment by igo95862** [comment]
Are you using some old version?

**Comment by bencejuhaasz** [comment]
I switched to Artix Linux, the aur package and having the latest packages from everything solved this, thanks for the quick reply. (The distro at fault was void, with not updating the needed packages)
