### ISSUE TITLE
FYI: Fedora (rpm) packageing 

### ISSUE THREAD

**Issue by rusty-snake** [igo95862/bubblejail#28]
FYI I've wrote a bubblejail.spec. If users of Fedora (or other rpm-based distros) want to use it to create a package before installing bubblejail https://github.com/rusty-snake/fedora-extras/tree/main/bubblejail might be helpful.

**Comment by igo95862** [comment]
Thank you.

You probably need this patch on Fedora: 

https://github.com/h0cheung/copr-packages/blob/master/bubblejail/ca_path_fix.patch

I am primary Arch Linux user and every distro has its own unique quirks.

**Comment by rusty-snake** [comment]
> https://github.com/h0cheung/copr-packages/blob/master/bubblejail/ca_path_fix.patch

Interesting. I did not hit it so far but I don't use bubblejail that much (yet). But it is correct if you need the OS ca-certs.

Is there any reason you did not added this to bubblejail so far?

**Comment by igo95862** [comment]
> Is there any reason you did not added this to bubblejail so far?

Because there is no such directory on Arch Linux.

I might add the newly added `ReadOnlyBindTry` but I am not sure at the moment.

I also have a plan to pass entire `/etc` to sandbox. (it will depend on how backward compatible such change will be)

**Comment by igo95862** [comment]
@rusty-snake I added a link to your .spec file to README. Thank you for packaging bubblejail.
