### ISSUE TITLE
which: not found 

### ISSUE THREAD

**Issue by codeInTheShell** [igo95862/bubblejail#29]
Copied the existing firefox profile to /usr/local/share/bubblejail/profiles/firefox-esr.toml

And adjusted the config like so:

`# Firefox on X11
dot_desktop_path = "/usr/share/applications/firefox-esr.desktop"
is_gtk_application = true
description='''
Firefox web browser.
'''

import_tips='''
Move .mozilla folder from your home directory in to instance
home directory.
'''

#[import_conf]
#copy = [".mozilla"]

[services.common]
executable_name = "/usr/bin/firefox-esr"
[services.x11]
[services.network]
[services.pulse_audio]
[services.notify]

[services.home_share]
home_paths = [ "Downloads",]
`

Created a new instance called firefox-esr via UI but running it results in the error below:
`$ bubblejail run firefox-esr
b'/usr/bin/firefox-esr: 1: which: not found\n'
b'Terminated\n'
`

While which tells me the binary is where it's supposed to be 
`$ which firefox-esr
/usr/bin/firefox-esr
$ ll /usr/share/applications/firefox-esr.desktop
-rw-r--r-- 1 root root 9277 Mär 31 08:18 /usr/share/applications/firefox-esr.desktop
`

**Comment by igo95862** [comment]
Can you run `--debug-shell` and try to execute `which` from within?

**Comment by codeInTheShell** [comment]
`$ bubblejail run --debug-shell firefox-esr
$ which firefox-esr
/bin/sh: 1: which: not found
`

**Comment by igo95862** [comment]
Run `which --help`

**Comment by codeInTheShell** [comment]
Same, not found

**Comment by igo95862** [comment]
Ok, run `which which` outside sandbox

**Comment by codeInTheShell** [comment]
`$ which which
/usr/bin/which
`

**Comment by igo95862** [comment]
Does `/usr/bin/which` work inside sandbox?

**Comment by codeInTheShell** [comment]
Nope. Seems to not be there.

> $ bubblejail run --debug-shell firefox-esr
$ /usr/bin/which
/bin/sh: 1: /usr/bin/which: not found

**Comment by igo95862** [comment]
WTF. Is it a symlink?

**Comment by codeInTheShell** [comment]
```
ll /usr/bin/which
lrwxrwxrwx 1 root root 23 Apr 14 17:01 /usr/bin/which -> /etc/alternatives/which*
```

**Comment by igo95862** [comment]
You will need to pass `/etc/alternatives` to the sandbox. (for example with `--debug-bwrap-args`)

**Comment by codeInTheShell** [comment]
As what option though?
I checked the 22.04 live cd and this appears to be same setup there with this symlink nonsense. That being the new way of doing things apparently, wouldn't it make more sense to do a check on the file and follow the symlink? Otherwise other distro users (no idea who does this other than canonical) would all have to do extra adjustments to get this running.

**Comment by igo95862** [comment]
Like that: `bubblejail run --debug-bwrap-args ro-bind /etc/alternatives /etc/alternatives -- firefox-esr /usr/bin/firefox-esr`

> I checked the 22.04 live cd and this appears to be same setup there with this symlink nonsense. That being the new way of doing things apparently, wouldn't it make more sense to do a check on the file and follow the symlink? Otherwise other distro users (no idea who does this other than canonical) would all have to do extra adjustments to get this running.

It's a Ubuntu/Debian thing. I am primarily developing for Arch Linux. Whoever packages bubblejail for Debian/Ubuntu would need to add extra compatibility patches just like Fedora and Alpine Linux packagers do.

**Comment by igo95862** [comment]
Also I have no idea why `firefox-esr` calls which. If it did not do that or `/usr/bin/which` would be an actual binary there would not be any need for these hacks.

**Comment by codeInTheShell** [comment]
My bad I forgot about package management. 
Tried your command, works for me. Thanks for you help.
