### ISSUE TITLE
Any chance you have a Patreon?

### ISSUE THREAD

**Issue by Dyras** [igo95862/bubblejail#3]
Greetings! I would like to donate towards development. Any chance you have a patreon?

**Comment by igo95862** [comment]
I will look in to it if there is interest.

**Comment by igo95862** [comment]
I added the my Patreon to the funding file. Here is the link: https://www.patreon.com/igo95862

I've made a first post on it with a bubblejail's roadmap in close future.

> I think Liberapay would make more sense.

I will look in to it.
