### ISSUE TITLE
Help wanted: testing the etc sharing branch

### ISSUE THREAD

**Issue by igo95862** [igo95862/bubblejail#31]
Link to branch: https://github.com/igo95862/bubblejail/tree/etc-sharing

This is a pretty big change that `/etc` is now passed entirely in to the sandbox.

There is a potential that this would cause the existing sandboxes to be broken.

I tested some of my sandboxes but it seems to be working fine.

Any help testing this big change would appreciated.

**Comment by igo95862** [comment]
@djpohly @donob4n @codeInTheShell @kiasoc5 @h0cheung @bencejuhaasz @sad-goldfish @gnusenpai

**Comment by sad-goldfish** [comment]
I created a Firefox instance in 0.5.3 and, as before, it hung. After upgrading bubblejail to the etc-sharing branch and using the same instance, firefox works. Lutris and chromium also seem to work in the new branch.

**Comment by sad-goldfish** [comment]
`hostname --fqdn` also works and returns the expected result

**Comment by igo95862** [comment]
I added 230a96c6a0e9184fe1c5a184a972f91763bf45be that will send a desktop notification if running bubblejail instance fails. This should help migrating to newer versions if some of the changes could cause instances to break. It uses the `notify-send` from libnotify currently. (will be migrated to dbus later)

**Comment by kiasoc5** [comment]
Firefox and steam work with 0.5.3.

**Comment by igo95862** [comment]
> Firefox and steam work with 0.5.3.

So they don't work on a new branch?

**Comment by kiasoc5** [comment]
> > Firefox and steam work with 0.5.3.
> 
> So they don't work on a new branch?

Yes I meant to say they work on the new branch.  Sorry for the mixup.

**Comment by gnusenpai** [comment]
My Firefox instance is working mostly as expected. My cursor theme is no longer being respected so I had to manually change it with `lxappearance`. I will update if I find any issues.

**Comment by igo95862** [comment]
Thanks everyone for testing.

Seems like the change is very backwards compatible. This made me decide to go with another potentially difficult change. 04101ad7207908957474f8716b38a25f58dc50f8

The home directory should now be in same place from the perspective of sandbox as it is outside the sandbox. This means there is no need to rewrite paths to home directory.

**Comment by igo95862** [comment]
I decided to merge the branch and release 0.6.0

Thank you again for testing.
