### ISSUE TITLE
Help wanted: create new icon

### ISSUE THREAD

**Issue by igo95862** [igo95862/bubblejail#33]
Current icon: ![Current logo](https://raw.githubusercontent.com/igo95862/bubblejail/master/data/bubblejail-config.svg)

It was done very quickly and has a droplet not a bubble.

During testing the notifications it turned out that it looked very bad on dark background.

Requirements for new icon:

1. Look good on both bright and dark themes.
2. Formats: 48x48 PNG and vectored SVG
3. Not contain any trade marks or copyrighted images

**Comment by iam-TJ** [comment]
How about this? Inspiration comes from a cold glass of amber beer!
![bubblejail01](https://user-images.githubusercontent.com/1151442/184626683-eb0042e1-29ea-450f-bb0c-aba22d452f81.svg)
![bubblejail](https://user-images.githubusercontent.com/1151442/184626696-3f311bcf-7f48-4eb7-9604-53a5595ed1ce.png)

**Comment by Nonie689** [comment]
I found many possible icons that with a bit editing could be candidates ... but some are maybe copyright protected and must be modified, to make them useable....

1. https://vectorified.com/images/anti-ddos-icon-20.png
2. https://vectorified.com/images/anti-ddos-icon-16.png
3. https://thumbs.dreamstime.com/z/ppe-icon-use-guards-protection-symbol-sign-black-background-vector-llustration-146687367.jpg
4. https://cdn3.iconfinder.com/data/icons/miscellaneous-33-solid/128/secure_safe_protection_conservancy_safety_security_defense-512.png
5. https://styles.redditmedia.com/t5_2w2qx/styles/communityIcon_fvtvlzziel551.png
6. https://geoportal.bayern.de/ba-backend/icons/ogImage
https://thumbs.dreamstime.com/z/save-water-sign-icon-hand-holds-blue-drop-symbol-environmental-protection-concept-vector-eps-63365153.jpg
7. https://vectorified.com/images/water-resistant-icon-10.jpg
8. https://media.istockphoto.com/vectors/icon-icon-for-home-security-protection-home-insurance-business-vector-id872690306?k=6&m=872690306&s=170667a&w=0&h=FmXjf9Qv_9psmZTColmZlaPFRw3FYi6KftWrsWHL--Y=
9. https://www.iconresources.com/new/images/sec_software_1.jpg
10. https://www.mohawkcollege.ca/sites/default/files/International/Images/arrivecan-logo.jpg
11. https://cdn1.iconfinder.com/data/icons/ecology-glyph-1/25/water_protect_ecology_nature_environmental_Protection_reserve__energy-512.png
12. https://thumbs.dreamstime.com/z/self-isolation-related-icons-set-background-graphic-web-design-creative-illustration-concept-symbol-mobile-app-178586058.jpg
13. https://www.soprema.ca/wp-content/uploads/2016/04/Isolation-hover.png


hmm hope this could help you or inspirate you...!

**Comment by gelatinbomb** [comment]
I tried to doodle some ideas for the icon. I think the latest is the closest to the concept of "bubble jail" but give me your opinion about it, if you have more ideas you can tell me to see if I can doodle more icons.
![Screenshot_20230520_203717](https://github.com/igo95862/bubblejail/assets/31792239/18eb1566-3e13-43ff-99a3-a3fc6f429309)

**Comment by igo95862** [comment]
> I tried to doodle some ideas for the icon. I think the latest is the closest to the concept of "bubble jail" but give me your opinion about it, if you have more ideas you can tell me to see if I can doodle more icons.

Pretty good art. Reminds me of some vintage fairytale illustrations.

Not sure why people make associations with beer?

**Comment by gelatinbomb** [comment]
I tried to explore the idea that the other dude posted. xD
But yeah maybe more exploration is needed.

**Comment by xiota** [comment]
Does Linux have icon overlays?  This way, an overlay (of a bubble) could be used with normal app icons.  Then in the app menu, apps run with bubblejail would have their icon shown inside of a bubble.  Would be nice if this could extend to the application itself.  Then it would be more obvious which apps are running sandboxed.

**Comment by gelatinbomb** [comment]
I tried to make more icons. You tell me what do you think it might work @igo95862 

@xiota I don't know if that's possible, seems like something it may vary depending of the desktop enviroment. I had the idea of copying the icon executable and then modifying it by adding the bubble on top of it. After that the modified icon gets store on a bubblejail folder or something like that.
![Icons](https://github.com/igo95862/bubblejail/assets/31792239/dc94e2a3-0964-4142-91bd-157b956d1d67)

**Comment by xiota** [comment]
I like the ones on the right that look like sketches.  The round bubble with a lock (second row, fourth from left).  It's simple and conveys the point.  Maybe give it a bluish tint.  Then the app icon can be desaturated slightly and put inside.  If there's no built-in way to overlay icons, it could probably be done without too much trouble with ImageMagick or PIL.  Maybe put the modified icon inside the instances folder?

A similar design might be to replace the lock with three or four vertical curved line "reflections", to make it look like a "bubblejail".

**Comment by gelatinbomb** [comment]
![icon](https://github.com/user-attachments/assets/f1751b9c-ffde-4a23-aa7c-113d75dbc7f9)
@igo95862 Did a vector one. The idea of the house have to do with the isolation of the files on bubblejail.

**Comment by igo95862** [comment]
Looks good! Nice and clean.

**Comment by gelatinbomb** [comment]
@igo95862 Nice! If you want you can use that icon since is in a .svg already. If you have any feedback tell me so I can do the corrections.

**Comment by gelatinbomb** [comment]
![icon_r1](https://github.com/user-attachments/assets/a81edfd8-0907-4ee9-874f-25e1a2c6acfc)
@igo95862 Like this?

**Comment by igo95862** [comment]
Yes. Thank you!

**Comment by igo95862** [comment]
I just added it to the repository. Big thank you to @gelatinbomb !
