### ISSUE TITLE
Missing `Type` in desktop entries

### ISSUE THREAD

**Issue by Henry-ZHR** [igo95862/bubblejail#36]
### Output of `bubblejail --version`

0.6.1

### Description

Key `Type` is required according to [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html).

KDE's Dolphin complains when you try to open the desktop entry.

**Comment by igo95862** [comment]
Do you mean that it is missing when generating empty desktop entry?

If you pass the `--desktop-entry` option to `generate-desktop-entry` when all the fields will be copied over.

**Comment by Henry-ZHR** [comment]
I mean it is missing in desktop entries created by `bubblejail create xxx`

**Comment by igo95862** [comment]
@Henry-ZHR see if 925f1cd87332533aaa894f4750e1a6a0aa7e8d90 fixes the issue.

**Comment by Henry-ZHR** [comment]
It works
