### ISSUE TITLE
Wrong xdg path with sudo - Fix needet at: bubblejail/bubblejail_directories.py

### ISSUE THREAD

**Issue by Nonie689** [igo95862/bubblejail#38]
### Output of `bubblejail --version`

r372.b7b2fa5

### Your distro name and version

archlinux-based

### Description

I think the xdg methode is suboptimal.

When I run bubblejail with sudo as normal user, 'bubblejail create --profiles generic %new-instancename' at:

'/root/.local/share/bubblejail/instances/ + instancename

I think os.getlogin() would be the better choice to use the correct path.
- first of all you need only to refactor some parts by the xdg_config_home, xdg_data_home at the /usr/lib/bubblejail/python_packages/bubblejail/bubblejail_directories.py file.

- then you could add also an parameter for setting an custom user with: 'bubblejail create --profiles generic %new-instancename --custom-user %username'

   cause when you the username = os.getlogin() it's just a step few to implement this also

 -  Then you can create a self made xdg_config_home and xdg_data_home by combine some vars to constructed the correct path.

hmmm if searched a bit, and the easiest or fastest way would be to use the a linux command with the python os.getlogin()

  ****PSEODO-CODE:

if not params.custom-user:
   username = os.getlogin()
else
   username = params.custom-user

xdg_data_home = exec_command "userdbctl | grep %username| awk '{print $6}' "

Hope I could help. But I believe you would find a python only nicer way. But I would speculate that the other way would be more code.

Alternative you find the correct userhome path in the /etc/passwd file. And I am not sure that this file is really on every system readable. This would be the only failure point.

Hope I could preworked a bit for your fixup...

Happy coding,

N689

**Comment by igo95862** [comment]
Uhh... Why would you run bubblejail as root? 🤔

**Comment by igo95862** [comment]
> * then you could add also an parameter for setting an custom user with: 'bubblejail create --profiles generic %new-instancename --custom-user %username'

You can do `sudo -u %username bubblejail create --profiles generic %new-instancename`. It should in theory use the XDG directories for that user.

**Comment by Nonie689** [comment]
STDERR message: 

usage: bubblejail [-h] [--version] {run,create,list,edit,generate-desktop-entry} ...
bubblejail: error: unrecognized arguments: --profiles librewolf

**Comment by Nonie689** [comment]
Ooops wrong buttom clicked. So -> REOPEN

**Comment by Nonie689** [comment]
Ahh the profile parameter is without "s" character.

Yes... with sudo -u it sets the correct xdg path.

Hmm but I would say that this ERROR could happens often. So a workaround isn't userfriendly.

**Comment by Nonie689** [comment]
I hate this fucking bottum to close a issue! 

GGGGGGGGRRRRRR! HATRED. 

GITHUB SHOULD ASK ME, DO YOU WANT REALLY TO CLOSE IT!! -.-'

**Comment by igo95862** [comment]
> this ERROR could happens often

What error? The extra 's'?

There is a bash and fish auto completions to help enter options. (activated with Tab key)

**Comment by igo95862** [comment]
@Nonie689 any updates?

**Comment by Nonie689** [comment]
No errors. 

Can you alternative add a feature to add a profile for all users 

with [bubblejail create --profile generic]

listed with the command - >  userdbctl | grep regular | grep -wve "[↓|↑]" | awk '{print $6}'

PS: bubblejail failes when it is used with profiles, it needs without s ... on fast working, many users types profiles, can you add --profiles also and the short version -p

in bash style 
bubblejail create --profile generic] | bubblejail create --profiles generic] | bubblejail create -p generic]

in python:
profile or profiles or p

at the argument section

**Comment by igo95862** [comment]
> Can you alternative add a feature to add a profile for all users

Yes, there should be an `/etc/bubblejail/profiles` directory that profiles can be red from.

**Comment by Nonie689** [comment]
/etc/bubblejail/profiles doesn't helps - my /home/$username is encrypted by systemd-homed.

The only fixup would be to create an link from the /home/root/.local/share/bubblejail/

or set this folder as readable for others-type or changing the owner or group
and set this to readable

with chmod o+r  /home/root/.local/share/bubblejail/

ohhhhhhhwww !!!! PLEASE ANSWER MY MAIL!! I will write you somethink important new issue I have found!!

will write you to this mail:

igo95862 >at< yandex %dot% ru

**Comment by igo95862** [comment]
Sorry it is a difficult to understand you.

> /etc/bubblejail/profiles doesn't helps - my /home/$username is encrypted by systemd-homed.

I don't get why home has anything to do with it.

Right now profiles are red from two places: `$HOME/.config/bubblejail/profiles` and `/usr/share/bubblejail/profiles`

I will add `/etc/bubblejail/profiles` in the future. `/etc` directory is for system specific configuration.

**Comment by igo95862** [comment]
> * And I have no /etc/bubblejail/ folder, and I am not sure what you mean with  /etc/bubblejail/profiles exactly
>       you say "should be an /etc/bubblejail/profiles directory"

Sorry, I wanted to use a future tense. There is no such directory at the moment but I will add it in the future. Right now `/usr/share/bubblejail/profiles` should work for adding system wide profiles but not a best practice to modify files in `/usr`.

**Comment by Nonie689** [comment]
hmm ok. Thanks for your support.

PS: Great project you have done! Hope you will be let it active!

PPS: Ahh... hm somethin else what would be breaked if someone are creating an intances with sudo bubblejail create --profile generic  %instancename
are that the bubblejail-config are needet to run also as sudo to access them.

my opiniom is to disable "sudo bubblejail create --profile generic" generelly! This should be the easiest solution for now.

I have thinked now enough for 3 days! I think sudo should be rejected.

**Comment by igo95862** [comment]
I might block running bubblejail as root just because too many people try to do it for some reason. Probably because of firejail habits.

**Comment by igo95862** [comment]
> su %username

You can also do `sudo -iu %username` to log in as user.

**Comment by Nonie689** [comment]
PS: What way is the best to tell/report you a sec hole, without showing them at open github issues??

 igo95862 >at< yandex dottt ru is your email. But I think there should be an extra email for bubblejail cvs reports.
