### ISSUE TITLE
RE: Firefox gives "already running but not responding" 

### ISSUE THREAD

**Issue by e00E** [igo95862/bubblejail#4]
which you mention in TODO. I solved a similar issue so maybe this will help you. Feel free to close the issue whenever.

On my system I run wayland firefox by setting `MOZ_ENABLE_WAYLAND=1`. I run firefox unsandboxed but wanted to make sure that links I open from sandboxes would still open in that same firefox instance. To forward xdg-open out of the sandbox I use https://aur.archlinux.org/packages/snapd-xdg-open-git/ as explained in https://wiki.archlinux.org/index.php/Bubblewrap#Opening_URLs_from_wrapped_applications . At this point I would get the mentioned error message. In my case the fix was to set `MOZ_DBUS_REMOTE=1` and also ensure that the snapd-xdg-open dbus daemon uses my environment variables by running `dbus-update-activation-environment --systemd --all`.

**Comment by igo95862** [comment]
What version are you using?

https://github.com/igo95862/bubblejail/commit/550968edaf3bd9ec8493540baee7e5b5133cf85b This commit should have fixed issues with firefox.

**Comment by e00E** [comment]
Sorry,  I should have clarified that I am using bubblewrap directly. This project is interesting too which is why I thought this might be helpful information for you but clearly you're already aware.

**Comment by igo95862** [comment]
I could really use some help with Steam. It has some real weird quirks like crashing on startup if you pass system dbus and remembered a user.
