### ISSUE TITLE
Can't open bubblejail gui, all deps (should) be installed.

### ISSUE THREAD

**Issue by cynicsketch** [igo95862/bubblejail#41]
### Output of `bubblejail --version`

Alpine 0.6.2

### Your distro name and version

Alpine Linux edge

### Description

Basically, I can't open the bubblejail gui because it complains about PyQt5 not being found, though it is installed. I am no expert, so if I should file a complaint with somebody else, do let me know.

Output is below.

```
alpine:~$ bubblejail-config
Traceback (most recent call last):
  File "/usr/bin/bubblejail-config", line 9, in <module>
    from bubblejail.bubblejail_gui_qt import run_gui
  File "/usr/lib/python3.10/site-packages/bubblejail/bubblejail_gui_qt.py", line 22, in <module>
    from PyQt5.QtCore import QModelIndex
ModuleNotFoundError: No module named 'PyQt5'
alpine:~$ pip3 install PyQt5
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyQt5 in ./.local/lib/python3.10/site-packages (5.15.7)
Requirement already satisfied: PyQt5-sip<13,>=12.11 in ./.local/lib/python3.10/site-packages (from PyQt5) (12.11.0)
Requirement already satisfied: PyQt5-Qt5>=5.15.0 in ./.local/lib/python3.10/site-packages (from PyQt5) (5.15.2)
alpine:~$ bubblejail-config
Traceback (most recent call last):
  File "/usr/bin/bubblejail-config", line 9, in <module>
    from bubblejail.bubblejail_gui_qt import run_gui
  File "/usr/lib/python3.10/site-packages/bubblejail/bubblejail_gui_qt.py", line 22, in <module>
    from PyQt5.QtCore import QModelIndex
ModuleNotFoundError: No module named 'PyQt5'
alpine:~$ 

```

**Comment by igo95862** [comment]
Hello,

Can you try installing the PyQt5 from alpine package?

`sudo apk add py3-qt5`

**Comment by creamrat** [comment]
Fixed it. Odd that it isn't a declared dependency package.

@igo95862 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by igo95862** [comment]
> Fixed it. Odd that it isn't a declared dependency package.
> 
> @igo95862
> 
> Sent with [GitHawk](http://githawk.com)

Yes. Some dependencies are missing for Alpine package.

In think @donob4n planned to separate GUI and CLI in to different packages but I am not sure how much progress there was.

**Comment by donob4n** [comment]
Wops, I totally forgot about that. I think that I could do it this week.

**Comment by igo95862** [comment]
@donob4n I have a plan to add a notes that document every distro quirks running bubblejail. Can I add your user name and as Alpine Linux maintainer?

**Comment by donob4n** [comment]
I'm happy with that but I would like to be faster fixing problems on it. I hope to fix this today.

**Comment by donob4n** [comment]
I created the subpackage on https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/38631

@creamrat when you upgrade you will lose 'bubblejail-config', install 'bubblejail-config' and remove 'py3-qt5' (which should be kept as dependency)

'bubblejail-config' seems a better name than 'bubblejail-gui'

Regardless the other deps like 'desktop-file-utils' and 'libnotify' I think that they are better inside the desktop that the user install and let bubblejail silently ignore them if missing.

**Comment by igo95862** [comment]
> I created the subpackage

Looks great!

> Regardless the other deps like 'desktop-file-utils' and 'libnotify' I think that they are better inside the desktop that the user install and let bubblejail silently ignore them if missing.

I think I will add those details to the quirks page. I already added one for Void Linux.

**Comment by donob4n** [comment]
There is no pong from @cynicsketch but I feel that this could be closed.
