### ISSUE TITLE
Schroot combined with bubblejail

### ISSUE THREAD

**Issue by Nonie689** [igo95862/bubblejail#42]
### Description

I want to use 

https://wiki.debian.org/Schroot combined with bubblejail

is it better to bubblejail Schroot or is it better bubblejail the application in the Schroot??

**Comment by igo95862** [comment]
I think you want to schroot first. Bubblejail will block a lot of the syscalls.

**Comment by Nonie689** [comment]
hmmm have you maybe an idea how to get wayland in schroot?

**Comment by igo95862** [comment]
Hmmm. Thinking about this, schroot is probably be superseded by debootstrap new root file system and modifying bubblejail to use custom root. This will give full access to bubblejail services and independent file system.

**Comment by Nonie689** [comment]
I have read this... but not testet yet..

To run Wayland applications in docker without X, you need a running wayland compositor like Gnome-Wayland or Weston. You have to share the Wayland socket. You find it in XDG_RUNTIME_DIR and its name is stored in WAYLAND_DISPLAY. As XDG_RUNTIME_DIR only allows access for its owner, you need the same user in container as on host. Example:

source:

https://unix.stackexchange.com/questions/330366/how-can-i-run-a-graphical-application-in-a-container-under-wayland

**Comment by Nonie689** [comment]
and I have found this..

https://laurentschneider.com/wordpress/2007/03/xhost-is-a-huge-security-hole.html

**Comment by igo95862** [comment]
> make a softlink from the xdg runtime dir to the chroot???

You need to create the xdg runtime dir inside the chroot and then link the wayland socket. (this is what bubblejail does for wayland)

BTW I feel like this issue went of topic. Sorry I can't help with schroot or systemd-nspawn because I am not familiar with either one of them. Should I close the issue?

**Comment by Nonie689** [comment]
No... what do you think to use unionfs to make the root fs secure instead of chroot?

**Comment by igo95862** [comment]
> No... what do you think to use unionfs to make the root fs secure instead of chroot?

Bubblejail already makes root secured.

**Comment by Nonie689** [comment]
Can you make a description what bubblejail currently do?

**Comment by igo95862** [comment]
> Can you make a description what bubblejail currently do?

I had plans to make a document with architecture explanation.
