### ISSUE TITLE
Since 0.7.0 build requires extra dependencies

### ISSUE THREAD

**Issue by igo95862** [igo95862/bubblejail#47]
I can't speak for the exact state of the COPR build infra, but I suspect it starts with an extremely barebones installation that does _not_ have those packages installed. I can only say that when I add `tomli` and `pyxdg` to the "build requires" section, the build succeeds.

_Originally posted by @j39m in https://github.com/igo95862/bubblejail/issues/46#issuecomment-1438155574_

**Comment by igo95862** [comment]
The solution is to separate the argument parser metadata to separate module.

**Comment by igo95862** [comment]
This should be fixed after bfe2730671804690b61fd214ce2521b8ec6bd1f3 and 99b3c72f71b34dbb80dfc9ecdd5882944c733c9c.

@j39m can you give it a test?

**Comment by j39m** [comment]
Works perfectly for me in COPR — no unexpected imports during doc generation, and I can move all those packages back into pure runtime dependencies. Thanks for the quick fixes!
