### ISSUE TITLE
Problem importing PGP Keys

### ISSUE THREAD

**Issue by aninternetuserx** [igo95862/bubblejail#5]
Hi, in the last days I've been trying to install the package available on the AUR but I'm not able to import the PGP signature. The error I get is `gpg: keyserver receive failed: No data`.
I've also tried to manually import the keys but I get the same message. Any chance to fix this so as to download it? Thank you so much

**Comment by igo95862** [comment]
https://github.com/mailvelope/keyserver/issues/108 Seems like GPG server key issue.

Here is the key:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

xjMEXi+3DhYJKwYBBAHaRw8BAQdAIoAeYBxPsLofRlh+Z13QSm0q8CsAUjxm
bHpj+0zQPgvNHWlnbzk1ODYyIDxpZ285NTg2MkB5YW5kZXgucnU+wqcEExYI
ADgWIQRaPQZXampnRD376FbxpV5ilRshQwUCXi+3DgIbAwULCQgHAgYVCgkI
CwIEFgIDAQIeAQIXgAAhCRDxpV5ilRshQxYhBFo9BldqamdEPfvoVvGlXmKV
GyFDU/AA/0SBRrpGOkHX0K2M2pUwRhltRfkzBE51v96n/vA2yfWiAP9KWVgP
OhLPf4n06hkJTemNfhBxmlNSe4mnY0YKJ8oeCM44BF4vtw4SCisGAQQBl1UB
BQEBB0CFT4t9i6/XH0avzkxcTkhISYmXGx8NE7xn6R3xFYhcXQMBCAfCjwQY
FggAIBYhBFo9BldqamdEPfvoVvGlXmKVGyFDBQJeL7cOAhsMACEJEPGlXmKV
GyFDFiEEWj0GV2pqZ0Q9++hW8aVeYpUbIUNnzgD/YySIhqC5gZHyqRUxM/IQ
pnIVSfkq62nPQm8djAPUOxEA/jYiO1jmJpmje6rIrJO5PsGXFazuyr2cMqZo
3u7VcNIE
=hwGX
-----END PGP PUBLIC KEY BLOCK-----
```

You can also try `--skippgpcheck` for makepkg or use the -git version which does not verify the gpg signature.

**Comment by igo95862** [comment]
Ok I tried Ubuntu key server and its working but only if you use curl directly instead of searching. Not sure why.

`curl -s 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x5a3d06576a6a67443dfbe856f1a55e62951b2143' | gpg --import`

I will close it for now. If you have any other issues please re-open.
