### ISSUE TITLE
Add profiles for Mullvad Browser and Tor Browser

### ISSUE THREAD

**Issue by Dyras** [igo95862/bubblejail#58]
### Description

Hello! Just wanted to request profiles for Mullvad Browser and Tor Browser.

That is all! Keep up the good work!

**Comment by igo95862** [comment]
Hello,

Have you tried re-using profile like described in this wiki article:

https://wiki.archlinux.org/title/Bubblejail#Re-using_profile_for_similar_applications

I believe Tor Browser is used based on Firefox.

**Comment by igo95862** [comment]
See [Example: setting up Torbrowser](../wiki/Example:-setting-up-Torbrowser) and [Re‐using profiles for similar applications.](../wiki/Re‐using-profiles-for-similar-applications.-Example-with-qutebrowser-and-chromium.) on how to setup a particular application that does not have a profile.
