### ISSUE TITLE
Relative paths 

### ISSUE THREAD

**Issue by ls0h** [igo95862/bubblejail#6]
Hello!

I am interested in your project. And I want to test it. But I don't want to install it systemwide now. It would be great to make directory paths relative to main executable. 
Replace 
`path.append('/usr/lib/bubblejail/python_packages')`
with
```
import os
path.append(os.path.dirname(__file__) + '/../lib/bubblejail/python_packages')
```
or something like that. So bubblejail can be installed not only in /usr.

Thanks!

**Comment by igo95862** [comment]
I see.

I think its a build system feature. Particularly meson has `--prefix` argument. I think I will make that meson will configure binaries to use specified prefix instead of hard coded one. It is a bit too Arch Linux centered right now.

**Comment by ls0h** [comment]
Then I have a question. How do you test bubblejail during development? Reinstallation after every code update?
I want to try implement some features, but do not know how to do that without systemwide installation. Is it possible to run bubblejail from development directory?
Thanks!

**Comment by igo95862** [comment]
I think I will add a HACKING.md guide that documents how you can test your changes. (for example, there is a special parameter to pass helper code to test helper changes)

@ls0h Anything else you having issues with?

**Comment by ls0h** [comment]
I have not found other problems. Thank you. Now I'm trying to figure out how this works under the hood.

**Comment by igo95862** [comment]
If you use `--dry-run` option with run command you will see the list of arguments that will be passed to bwrap and dbus proxy.
