### ISSUE TITLE
Add ability to share files (not just folders)

### ISSUE THREAD

**Issue by xiota** [igo95862/bubblejail#60]
### Description

Would like the ability to share specific files with applications, via home share or root share.  Would be good if access could be made read-only.

For example, programs need access to `~/.config/mimeapps.list` to be able to open documents with the correct apps.  However, sharing the entirety of `~/.config` somewhat defeats the purpose of sandboxing.  Read-only would be useful to prevent apps from hijacking file associations.

**Comment by igo95862** [comment]
Hello @xiota 

I am pretty sure the current root and home share support files.

Root share has a read only option and adding one to home share should be trivial.

**Comment by xiota** [comment]
I just tried, and sharing files with home share seems to work.  Wasn't clear to me that files would work because the interface specifically says "directories".  `bwrap` documentation about all the `--*-bind-*` options also wasn't clear to me.

**Comment by igo95862** [comment]
The documentation could improved.

**Comment by xiota** [comment]
Thank you for the update: 88033a38f2582c897de498811bb8330230597d16
