### ISSUE TITLE
After program crashes: Instance already running.

### ISSUE THREAD

**Issue by xiota** [igo95862/bubblejail#79]
### Output of `bubblejail --version`

AUR-git 0.8.2.r1.g547c469

### Your distro name and version

Arch

### Description

Sometimes, the program I'm running crashes (usually Firefox, but has happened with a few other GUI programs).  Then every subsequent rerun attempt until reboot has an error message:

<details><summary>Instance already running...</summary>

```
Instance already running.
Sending command to the instance:  []
Traceback (most recent call last):
  File "/usr/bin/bubblejail", line 32, in <module>
    bubblejail_main()
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 243, in bubblejail_main
    func(**args_dict)
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 94, in run_bjail
    command_return_text = async_run(
                          ^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_instance.py", line 166, in send_run_rpc
    (reader, writer) = await open_unix_connection(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 98, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 259, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 642, in _sock_connect
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```
</details>

This happens infrequently, ~~maybe 0-2/week.  I haven't noticed any pattern or condition leading to the crashes.~~  Seems like a workaround would be some way to clear whatever is causing bubblejail to detect that an instance is already running.  (Appears to be related to [many hours of autoplay](https://github.com/igo95862/bubblejail/issues/79#issuecomment-1873573612) on a particular website.)

This did happen before the 0.8.2 release, but it was easier to ignore because the other issue was so dominant.

Last time it happened, one program/instance crashed, and every other program/instance I tried to run showed the same error message.  So, Firefox crashed.  Then I tried to switch to Chromium.  Then I tried to switch to Edge.  Don't know if it was coincidence they all had the same problem or if they were all connected.

They all have their own separate instance / bubblejail config.  Not trying to use a single instance to run different programs.

**Comment by igo95862** [comment]
Hello @xiota 

When it happens again can you check that `bubblejail-helper` is still running?

```
>>> ps aux | grep 'bubblejail-helper'
igo95862    5321  0.0  0.0   2720  1792 ?        S    13:23   0:00 /usr/bin/bwrap --args 14 -- /usr/lib/bubblejail/bubblejail-helper --helper-socket 6 --ready-fd 12 -- /usr/lib/firefox/firefox
```

**Comment by igo95862** [comment]
BTW if you want to re-launch the crashed instance just remove it's runtime directory.

For example,

```
rm -r /run/user/1000/bubblejail/Firefox/
```

**Comment by xiota** [comment]
I haven't had any crash recur yet.  I will check `ps aux` and `/run/user/...` next time it happens.  I think bubblejail is incidental to the crash itself.  Is there a way to force a program to crash to see if that replicates the issue?

**Comment by igo95862** [comment]
You can crash it by sending a SIGSEGV signal but that does not really help solve this issue.

The issue is:

1). `ConnectionRefusedError: [Errno 111] Connection refused` is because the helper is no longer responding.
2). Why is it no longer responding?
3). Did it already stop running and bubblejail parent program did not preform the cleanup? Usually after the helper exits the `bwrap` also finishes and bubblejail parent will stop waiting and will perform the clean-up.
4). So either the bubblejail parent thinks the helper is still running or bubblejail parent itself crashed and did not perform the clean-up.

Also the `journalctl` should contain the stderr of both bubblejail and the helper.

**Comment by xiota** [comment]
The problem hasn't recurred since I opened it, so probably much more rare than I estimated or previous issue that was resolved with 0.8.2 caused it to occur more frequently.

Off topic question, not sure where else to ask, is it possible to disable specific cpu features, make it behave like a different processor?  Asking from curiosity, not as potential feature.

**Comment by igo95862** [comment]
> Off topic question, not sure where else to ask, is it possible to disable specific cpu features, make it behave like a different processor? Asking from curiosity, not as potential feature.

There does seem to be a way to do so in the glibc but it is poorly supported: https://stackoverflow.com/questions/42451492/disable-avx-optimized-functions-in-glibc-ld-hwcap-mask-etc-ld-so-nohwcap-for

**Comment by xiota** [comment]
Thanks for the link about disabling avx.  It answers what I was wondering.

Saw the instance already running error after force closing Firefox because it had frozen while playing movies.  But the error was gone by the time I had navigated to this page with a different browser in another bubblejail instance.

**Comment by igo95862** [comment]
> Saw the instance already running error after force closing Firefox because it had frozen while playing movies. But the error was gone by the time I had navigated to this page with a different browser in another bubblejail instance.

Could be a Firefox bug. Bubblejail simply checks if there are processes still running to determine when to shutdown instance. If some instance has a hang-up processes bubblejail will think it is still running.

**Comment by xiota** [comment]
Think you're right.  Happened again while playing videos in Firefox.  This time persisted.  `ps aux` didn't show bubblejail running at all.  The bubbleajail folders in `/run/user` were present, and deleting them resolved the issue.

Would it be worth having `bubblejail` check and clean up the folders?  Or should I add them to my garbage collection script?

**Comment by igo95862** [comment]
> `ps aux` didn't show bubblejail running at all. The bubblejail folders in `/run/user` were present, and deleting them resolved the issue.

If bubblejail was no longer running but folder were still present then it should have crashed in a way that did not unwind all the context managers. (like segmentation error) Is there anything in the journalctl?

**Comment by xiota** [comment]
My `journalctl` doesn't store going back that far.  I'll check next time it happens.

**Comment by xiota** [comment]
I think the problem website is `tubitv.com`.  It doesn't have an option to disable autoplay, so if I'm distracted, it will keep playing forever.  Then when close the tab, the browser freezes and has to be force closed.  Happens after many hours of autoplay, not just a few videos.

May or may not be relevant, `journalctl` has some lines like following:
```
plasmashell[54655]: [6269] Sandbox: attempt to open unexpected file /sys/devices/system/cpu/cpu0/cache/index2/size
plasmashell[54655]: [6269] Sandbox: attempt to open unexpected file /sys/devices/system/cpu/cpu0/cache/index3/size
plasmashell[54655]: [6269] Sandbox: attempt to open unexpected file /sys/devices/system/cpu/present
plasmashell[54655]: [6269] Sandbox: attempt to open unexpected file /sys/devices/system/cpu/possible
plasmashell[28113]: Exiting due to channel error.
plasmashell[50024]: Exiting due to channel error.
plasmashell[65008]: Exiting due to channel error.
plasmashell[27818]: Exiting due to channel error.
plasmashell[27771]: Exiting due to channel error.
plasmashell[65110]: Exiting due to channel error.
plasmashell[52709]: Exiting due to channel error.
plasmashell[65197]: Exiting due to channel error.
plasmashell[65048]: Exiting due to channel error.
plasmashell[27654]: Terminated
```

`bubblejail` was able to recover after only one failed rerun attempt.

**Comment by igo95862** [comment]
I have an idea of a `bubblejail ps` command that will print the currently running sandboxes and the number of processes they have. (and some other stats) This can make it easier to identify when a sandbox is not terminating because of some hang-up process.

**Comment by xiota** [comment]
`bubblejail ps` could be useful, especially to find instances for programs that spawn multiple services that are difficult to track down and close.  Then maybe `bubblejail kill` to get rid of them.
