### ISSUE TITLE
Documentation on homedir location

### ISSUE THREAD

**Issue by firefoxlover** [igo95862/bubblejail#86]
### Description

So far it works great! But where is the seperate home directory?

Opening the profile dir from Firefox through about:profiles did not work.

**Comment by igo95862** [comment]
Hello @firefoxlover 

The instance home directory is usually located at `~/.local/share/bubblejail/instances/<instances_name>/home/`.

> Opening the profile dir from Firefox through about:profiles did not work.

Most likely the file browser crashes. For example, GNOME Files wants to bind to a specific D-Bus address that the sandbox does not allow.

**Comment by rusty-snake** [comment]
> Most likely the file browser crashes. For example, GNOME Files wants to bind to a specific D-Bus address that the sandbox does not allow.

It's also possible the firefox uses a portal for this. Nevermind, if firefox ask a your file-manager to open `~/.mozilla/firefox/foobar` from its vfs view, and the filemanager tries to open this from host vfs view it will not work either.

**Comment by firefoxlover** [comment]
Thanks! I will see. Can we preset stuff for the firefox profile? For example enable the portal, which is not enabled by default? Probably out of scope as the profilen created gets a random ID?

Also on KDE it uses 100% GNOME style and I dont know why. Maybe some directories need to be allowed? But thats a different issue.

**Comment by igo95862** [comment]
Portals integration will be completely reworked in some future versions. There will be some fine grained controls over which portals the sandbox will be able to interact with.

> Also on KDE it uses 100% GNOME style and I dont know why.

I am not entirely familiar how Firefox picks the style.

**Comment by rusty-snake** [comment]
GTK3 theme configuration is stored in dconf.

**Comment by igo95862** [comment]
Documented in 1a6e3f796ec1c4bf8867597dfa08916237e7d5e3
