### ISSUE TITLE
Support for Torbrowser

### ISSUE THREAD

**Issue by trytomakeyouprivate** [igo95862/bubblejail#90]
### Description

This is similar to #88 but includes that Torbrowser has a very specific filesystem structure.

This would need to be copied into the jail, and I would be curious how it could be done.

The GUI currently has no way of entering any variables, right? Because the torbrowser install location is currently random, copying those configs would not work.

**Comment by igo95862** [comment]
Hello @trytomakeyouprivate 

Have you tried manually installing the tor browser inside sandbox? You can run a terminal inside the sandbox to perform the necessary installation steps as well as running it.

> has a very specific filesystem structure

I am not familiar with it. Can it be run entirely from a user's home directory.

**Comment by trytomakeyouprivate** [comment]
Hey, havent got to it yet, but ill try for sure.

So first of all it would simply use the firefoxes sandbox. Special here are
- it doesnt use a binary in the PATH (by default)
- it basically does all the "fake home dir" already, which might be handy
- it has a signature and would be great to verify and make the success of box setup dependend on that [signature](https://www.torproject.org/dist/torbrowser/13.0.9/tor-browser-linux-x86_64-13.0.9.tar.xz.asc)
- it has a tar archive containing all the stuff [archive](https://www.torproject.org/dist/torbrowser/13.0.9/tor-browser-linux-x86_64-13.0.9.tar.xz)

So I suppose it would be great to create a box with the same filter as Firefox, and in there then execute the download commands, verify it (can we use GPG in such a container??), unpack it and move everything so that `launch-tor-browser.desktop` is in the right directory. This might just be possible by using their own official setup.

https://github.com/trytomakeyouprivate/Recommended-Flatpak-Apps/blob/main/Apps/Browsers.md#installation

**Comment by rusty-snake** [comment]
So effectively you want to run torbrowser-launcher in bubblejail.

**Comment by trytomakeyouprivate** [comment]
I think torbrowser-launcher is a helper tool that downloads the torbrowser files to a certain directory. If it is launched in the bubblejail, yes I guess that is the best option!

**Comment by trytomakeyouprivate** [comment]
```
❯❯❯ bubblejail run Torbrowser /usr/bin/torbrowser-launcher
Tor Browser Launcher
By Micah Lee & Tor Project, licensed under MIT
version 0.3.7
https://gitlab.torproject.org/tpo/applications/torbrowser-launcher/
Downloading Tor Browser for the first time.
Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/ALL
Error starting download:

https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/ALL

Are you connected to the internet?
```

**Comment by igo95862** [comment]
> I am getting connectivity problems?

You can launch the terminal in the sandbox to debug the connectivity problems. It could be the DNS issues like in #80

**Comment by igo95862** [comment]
I added a wiki page on how to [setup Tor browser](../wiki/Example:-setting-up-Torbrowser)

A profile is not planned because Tor browser requires a few manual steps that the current profile system can't handle.
