### ISSUE TITLE
chromium profile not working on Fedora (different package name)

### ISSUE THREAD

**Issue by trytomakeyouprivate** [igo95862/bubblejail#91]
### Output of `bubblejail --version`

0.8.2

### Your distro name and version

Fedora 39

### Description

Chromium on Fedora is called `/usr/share/applications/chromium-browser.desktop`. Does it need a new profile or simply an array with multiple locations? On Fedora the GUI spits out "no desktop entry found".

also it still uses X11, which is not needed anymore as Chromium has full Wayland support.

```
❯❯❯ bubblejail run chromium /usr/share/chromium                                                                                                            ✘ 2
Traceback (most recent call last):
  File "/usr/bin/bubblejail", line 32, in <module>
    bubblejail_main()
  File "/usr/lib64/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 243, in bubblejail_main
    func(**args_dict)
  File "/usr/lib64/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 80, in run_bjail
    instance = BubblejailDirectories.instance_get(instance_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/bubblejail/python_packages/bubblejail/bubblejail_directories.py", line 93, in instance_get
    raise BubblejailInstanceNotFoundError(instance_name)
bubblejail.exceptions.BubblejailInstanceNotFoundError: chromium
```

**Comment by igo95862** [comment]
Hello @trytomakeyouprivate 

Do you have an exact error? Try running bubblejail in the terminal.

**Comment by trytomakeyouprivate** [comment]
edited, the github template ate my description

**Comment by rusty-snake** [comment]
> /var/home/user/~/Downloads

1. Are you sure that you want `~/\~/Downloads` (the second `~` is literal) rather than `~/Downloads`?
2. You use a immutable version like silverblue.

**Comment by trytomakeyouprivate** [comment]
strange, this must be the GUI. I set the allowed folder to be `~/Downloads` and it must have added the part before.

**Comment by igo95862** [comment]
The `~` is actually shell magic. If you want to share something relative to home you should use home share service.

**Comment by igo95862** [comment]
Not an issue.

The GUI probably needs a file picker instead of raw string input. This would prevent someone from entering `~/Downloads` in to the options.

> /usr/share/, /usr/etc/, /etc/chromium: rw
> /usr/bin/ : ro

The `/usr` and `/etc` should already be shared read-only by default with sandbox. Not sure why you have manually added them.
