### ISSUE TITLE
ALSA: open /dev/snd/seq failed

### ISSUE THREAD

**Issue by xiota** [igo95862/bubblejail#93]
### Output of `bubblejail --version`

AUR-git 0.8.2.r3.g1a6e3f7

### Your distro name and version

Arch

### Description

<details><summary>The problem with Opera is I had added <tt>/dev</tt> to root share while trying to run another program...</summary

Opera 107.0.5045.15 (built from [`aur/opera`](https://aur.archlinux.org/packages/opera)) fails to run and produces the following errors:
```
Failed to open /dev/null
Failed to open /dev/null
[2:2:0209/023946.469393:FATAL:zygote_host_impl_linux.cc(202)] Check failed: . : No such file or directory (2)
[0209/023946.471552:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/online: No such file or directory (2)
[0209/023946.479961:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[0209/023946.480039:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
```

I would prefer not to give access to these devices, but to fake access and silently ignore the error.
</details>

The other program is [ZQuest Classic](https://github.com/ZQuestClassic/ZQuestClassic/). The error is:
```
ALSA lib seq_hw.c:528:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
```
Adding either `/dev` or `/dev/snd/seq` to root share as rw or ro changes the error to:
```
ALSA lib seq_hw.c:528:(snd_seq_hw_open) open /dev/snd/seq failed: Permission denied
```

**Comment by igo95862** [comment]
Hello @xiota 

I believe `/sys/devices/system/cpu/` is used to get the topology of the CPU. Have you tried mounting it read-only? Steam profile already does that.

**Comment by xiota** [comment]
I found the problem with Opera.  I had added `/dev` to root share because I was trying to run another program...

Other program is [ZQuest Classic](https://github.com/ZQuestClassic/ZQuestClassic/).  Error is:
```
ALSA lib seq_hw.c:528:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
```
Adding either `/dev` or `/dev/snd/seq` to root share as rw or ro makes no difference.  I'll update initial post with this info.

**Comment by igo95862** [comment]
Yes, ALSA would probably require its own service. However, I am pretty sure most programs use PulseAudio or Pipewire directly. Are there a build flags or environment variables you add to not use ALSA?

**Comment by xiota** [comment]
The program has an option that looks like it's supposed to use pulseaudio, but nothing happens when I change it.  The program probably needs to be rebuilt to switch audio sources.  I'm willing to not use programs that don't work with modern sound servers.

**Comment by igo95862** [comment]
I am not planning on adding ALSA service because most applications can use PulseAudio and the most modern ones can use the Pipewire.

See if you can use the new `debug` service to allow this applications to access `/dev/snd/`. (something like `["--dev-bind", "/dev/snd/", "/dev/snd/"]`)
