### ISSUE TITLE
[Req] Add option to add environment variables

### ISSUE THREAD

**Issue by xiota** [igo95862/bubblejail#94]
### Description

Would be nice to have option to add environment variables.  Currently able to use:
```
bubblejail run instance env var=val /path/to/executable
```

**Comment by igo95862** [comment]
Hello @xiota 

I am planning on adding a new service which would be used to configure bwrap directly: https://github.com/igo95862/bubblejail/issues/85#issuecomment-1879632645

**Comment by xiota** [comment]
Editing `services.toml` with the following:
```
[debug]
raw_bwrap_args = [
    "--setenv X Y",
]
raw_dbus_session_args = []
raw_dbus_system_args = []
```

Produces the following message:
```
bwrap: Unknown option --setenv X Y
```

However, the following works:
```
[debug]
raw_bwrap_args = [
    "--setenv",
    "X",
    "Y",
]
raw_dbus_session_args = []
raw_dbus_system_args = []
```

Would be nice if arguments are split on space so that related options can be kept together.

**Comment by igo95862** [comment]
> Produces the following message:

Yes, this is because those are raw arguments that are passed to bwrap. Separating on spaces is actually a shell thing.
