### ISSUE TITLE
Doesnt detect Fedora Chromium

### ISSUE THREAD

**Issue by boredsquirrel** [igo95862/bubblejail#97]
### Output of `bubblejail --version`

0.8.3

### Your distro name and version

Fedora 39 Kinoite

### Description

I have Chromium layered (installed as RPM), and it is called `chromium-browser` for some reason on fedora, which makes bubblejail not only give an error message "no desktop entry found" but even worse block the usage of the chromium preset.

detecting `chromium` OR

**Comment by igo95862** [comment]
Hello @trytomakeyouprivate 

Interesting.

By the way is it only the binary that is called `chromium-browser` or is the desktop entry also called `chromium-browser.desktop`?

**Comment by trytomakeyouprivate** [comment]
both the binary and the desktop entry are called chromium-browser

/usr/bin/chromium-browser

/usr/share/applications/chromium-browser.desktop

**Comment by rusty-snake** [comment]
Fedora, OpenSUSE, Ubuntu/Mint seem to have a `chromium-browser.desktop`. Some more distros like alpine have at least an additional `/usr/bin/chromium-browser` binary/symlink. See https://pkgs.org/search/?q=chromium.

Given that, do you still prefer to patch downstream?

**Comment by igo95862** [comment]
I decided to check the destkop entry names.

* [Alpine Linux: `chromium.desktop`](https://pkgs.alpinelinux.org/contents?branch=edge&name=chromium&arch=aarch64&repo=community)
* [Debian: `chromium.desktop`](https://packages.debian.org/bookworm/amd64/chromium/filelist)
* Ubuntu uses snap for chromium
* [OpenSUSE: looks like `chromium-browser.desktop` from build log](https://build.opensuse.org/package/live_build_log/network:chromium/chromium/openSUSE_Factory_ARM/aarch64)

**Comment by rusty-snake** [comment]
RPM based distros and Linux Mint? While Linux Mint is build on top of Ubuntu, they don't use snaps.

Upstream seem to use chromium-browser over chromium https://source.chromium.org/search?q=chromium-browser.desktop

**Comment by igo95862** [comment]
I guess it is worth adding support for multiple desktop entries paths for profiles.

For example, Firefox ESR on Debian uses `firefox-esr.desktop`: https://packages.debian.org/bookworm/amd64/firefox-esr/filelist

**Comment by igo95862** [comment]
Should be fixed in 57a8265c778d7b4c1a0af2b3d0d1d41cd1209514. Profiles now support a list of desktop entries and will pick the first found one. I added `firefox-esr.desktop` and `chromium-browser.desktop` as alternative names.

**Comment by igo95862** [comment]
@boredsquirrel could you give it a test?

I will close this issue for now. If it still can't find the desktop entry feel free to reopen it.
