### ISSUE TITLE
failed to run instance : instance_name "Exception : bubblejail.exceptions.BubblejailinstanceNotFoundError: instance name

### ISSUE THREAD

**Issue by guix01** [igo95862/bubblejail#98]
### Output of `bubblejail --version`

0.8.3

### Your distro name and version

archlinux rolling

### Description

Hi,
I red the documentation and I type 
"bubblejail create --profile firefox instance_name" and I cannot lauch firefox 

Now I can't launch firefox, only via the terminal, I don't have time to study bubblejail and I want to delete this message.
How can I delete this message and how can I restore Firefox without bubblejail?

Thanks you!

**Comment by igo95862** [comment]
Hello @guix01 ,

Look in to the `~/.local/share/applications/` folder. There should be a file called `firefox.desktop`. Delete it and update your desktop environment cache with `update-desktop-database ~/.local/share/applications/`.

**Comment by guix01** [comment]
Hello igo95862,

It works !

Thanks you very much.
